#*
#****************************************************************
#*	Makefile para a biblioteca "stdio"			*
#****************************************************************
#*
DIR	 = stdio
man_exec = DUMMY

.putenv man_exec

.virtual	n lint cp cmp man clr cmpinc
.virtual	pento penfrom pensave

stdio:
	cd atof;	make
	cd atoi;	make
	cd atol;	make
	cd cleanup;	make
	cd doprnt;	make
	cd doscan;	make
	cd error;	make
	cd fclose;	make
	cd fdopen;	make
	cd fflush;	make
	cd fgetc;	make
	cd fgetpos;	make
	cd fgets;	make
	cd fngets;	make
	cd fnputs;	make
	cd fopen;	make
	cd fprintf;	make
	cd fputc;	make
	cd fputs;	make
	cd fread;	make
	cd freopen;	make
	cd fscanf;	make
	cd fseek;	make
	cd fstatus;	make
	cd ftell;	make
	cd fwrite;	make
	cd gets;	make
	cd getw;	make
	cd popen;	make
	cd printf;	make
	cd puts;	make
	cd putw;	make
	cd readbuf;	make
	cd rewind;	make
	cd scanf;	make
	cd setbuf;	make
	cd setvbuf;	make
	cd siodata;	make
	cd snprintf;	make
	cd sprintf;	make
	cd sscanf;	make
	cd strtol;	make
	cd strtoul;	make
	cd ungetc;	make
	cd vfprintf;	make
	cd vprintf;	make
	cd vsnprintf;	make
	cd vsprintf;	make
	cd writebuf;	make

n:
	cd atof;	make -n
	cd atoi;	make -n
	cd atol;	make -n
	cd cleanup;	make -n
	cd doprnt;	make -n
	cd doscan;	make -n
	cd error;	make -n
	cd fclose;	make -n
	cd fdopen;	make -n
	cd fflush;	make -n
	cd fgetc;	make -n
	cd fgetpos;	make -n
	cd fgets;	make -n
	cd fngets;	make -n
	cd fnputs;	make -n
	cd fopen;	make -n
	cd fprintf;	make -n
	cd fputc;	make -n
	cd fputs;	make -n
	cd fread;	make -n
	cd freopen;	make -n
	cd fscanf;	make -n
	cd fseek;	make -n
	cd fstatus;	make -n
	cd ftell;	make -n
	cd fwrite;	make -n
	cd gets;	make -n
	cd getw;	make -n
	cd popen;	make -n
	cd printf;	make -n
	cd puts;	make -n
	cd putw;	make -n
	cd readbuf;	make -n
	cd rewind;	make -n
	cd scanf;	make -n
	cd setbuf;	make -n
	cd setvbuf;	make -n
	cd siodata;	make -n
	cd snprintf;	make -n
	cd sprintf;	make -n
	cd sscanf;	make -n
	cd stdio;	make -n
	cd strtol;	make -n
	cd strtoul;	make -n
	cd ungetc;	make -n
	cd vfprintf;	make -n
	cd vprintf;	make -n
	cd vsnprintf;	make -n
	cd vsprintf;	make -n
	cd writebuf;	make -n

lint:
	cd atof;	make lint
	cd atoi;	make lint
	cd atol;	make lint
	cd cleanup;	make lint
	cd doprnt;	make lint
	cd doscan;	make lint
	cd error;	make lint
	cd fclose;	make lint
	cd fdopen;	make lint
	cd fflush;	make lint
	cd fgetc;	make lint
	cd fgetpos;	make lint
	cd fgets;	make lint
	cd fngets;	make lint
	cd fnputs;	make lint
	cd fopen;	make lint
	cd fprintf;	make lint
	cd fputc;	make lint
	cd fputs;	make lint
	cd fread;	make lint
	cd freopen;	make lint
	cd fscanf;	make lint
	cd fseek;	make lint
	cd fstatus;	make lint
	cd ftell;	make lint
	cd fwrite;	make lint
	cd gets;	make lint
	cd getw;	make lint
	cd popen;	make lint
	cd printf;	make lint
	cd puts;	make lint
	cd putw;	make lint
	cd readbuf;	make lint
	cd rewind;	make lint
	cd scanf;	make lint
	cd setbuf;	make lint
	cd setvbuf;	make lint
	cd siodata;	make lint
	cd snprintf;	make lint
	cd sprintf;	make lint
	cd sscanf;	make lint
#	cd stdio;	make lint
	cd strtol;	make lint
	cd strtoul;	make lint
	cd ungetc;	make lint
	cd vfprintf;	make lint
	cd vprintf;	make lint
	cd vsnprintf;	make lint
	cd vsprintf;	make lint
	cd writebuf;	make lint

cp:
	cd atof;	make cp
	cd atoi;	make cp
	cd atol;	make cp
	cd cleanup;	make cp
	cd doprnt;	make cp
	cd doscan;	make cp
	cd error;	make cp
	cd fclose;	make cp
	cd fdopen;	make cp
	cd fflush;	make cp
	cd fgetc;	make cp
	cd fgetpos;	make cp
	cd fgets;	make cp
	cd fngets;	make cp
	cd fnputs;	make cp
	cd fopen;	make cp
	cd fprintf;	make cp
	cd fputc;	make cp
	cd fputs;	make cp
	cd fread;	make cp
	cd freopen;	make cp
	cd fscanf;	make cp
	cd fseek;	make cp
	cd fstatus;	make cp
	cd ftell;	make cp
	cd fwrite;	make cp
	cd gets;	make cp
	cd getw;	make cp
	cd popen;	make cp
	cd printf;	make cp
	cd puts;	make cp
	cd putw;	make cp
	cd readbuf;	make cp
	cd rewind;	make cp
	cd scanf;	make cp
	cd setbuf;	make cp
	cd setvbuf;	make cp
	cd siodata;	make cp
	cd snprintf;	make cp
	cd sprintf;	make cp
	cd sscanf;	make cp
	cd stdio;	make cp
	cd strtol;	make cp
	cd strtoul;	make cp
	cd ungetc;	make cp
	cd vfprintf;	make cp
	cd vprintf;	make cp
	cd vsnprintf;	make cp
	cd vsprintf;	make cp
	cd writebuf;	make cp

cmp:
	cd atof;	make cmp
	cd atoi;	make cmp
	cd atol;	make cmp
	cd cleanup;	make cmp
	cd doprnt;	make cmp
	cd doscan;	make cmp
	cd error;	make cmp
	cd fclose;	make cmp
	cd fdopen;	make cmp
	cd fflush;	make cmp
	cd fgetc;	make cmp
	cd fgetpos;	make cmp
	cd fgets;	make cmp
	cd fngets;	make cmp
	cd fnputs;	make cmp
	cd fopen;	make cmp
	cd fprintf;	make cmp
	cd fputc;	make cmp
	cd fputs;	make cmp
	cd fread;	make cmp
	cd freopen;	make cmp
	cd fscanf;	make cmp
	cd fseek;	make cmp
	cd fstatus;	make cmp
	cd ftell;	make cmp
	cd fwrite;	make cmp
	cd gets;	make cmp
	cd getw;	make cmp
	cd popen;	make cmp
	cd printf;	make cmp
	cd puts;	make cmp
	cd putw;	make cmp
	cd readbuf;	make cmp
	cd rewind;	make cmp
	cd scanf;	make cmp
	cd setbuf;	make cmp
	cd setvbuf;	make cmp
	cd siodata;	make cmp
	cd snprintf;	make cmp
	cd sprintf;	make cmp
	cd sscanf;	make cmp
	cd stdio;	make cmp
	cd strtol;	make cmp
	cd strtoul;	make cmp
	cd ungetc;	make cmp
	cd vfprintf;	make cmp
	cd vprintf;	make cmp
	cd vsnprintf;	make cmp
	cd vsprintf;	make cmp
	cd writebuf;	make cmp

man:
	cd atof;	make man
	cd atoi;	make man
	cd atol;	make man
	cd cleanup;	make man
	cd doprnt;	make man
	cd doscan;	make man
	cd error;	make man
	cd fclose;	make man
	cd fdopen;	make man
	cd ferror;	make man
	cd fflush;	make man
	cd fgetc;	make man
	cd fgetpos;	make man
	cd fgets;	make man
	cd fngets;	make man
	cd fnputs;	make man
	cd fopen;	make man
	cd fprintf;	make man
	cd fputc;	make man
	cd fputs;	make man
	cd fread;	make man
	cd freopen;	make man
	cd fscanf;	make man
	cd fseek;	make man
	cd fstatus;	make man
	cd ftell;	make man
	cd fwrite;	make man
	cd getc;	make man
	cd gets;	make man
	cd getw;	make man
	cd popen;	make man
	cd printf;	make man
	cd putc;	make man
	cd puts;	make man
	cd putw;	make man
	cd readbuf;	make man
	cd rewind;	make man
	cd scanf;	make man
	cd setbuf;	make man
	cd setvbuf;	make man
	cd siodata;	make man
	cd snprintf;	make man
	cd sprintf;	make man
	cd sscanf;	make man
	cd stdio;	make man
	cd strtol;	make man
	cd ungetc;	make man
	cd vfprintf;	make man
	cd vprintf;	make man
	cd vsnprintf;	make man
	cd vsprintf;	make man
	cd writebuf;	make man

clr:
	walk -p "*/?.o */? *bobo *garfield" . | rm -iN

cmpinc:
	cmp -l stdio/stdio.h $inc
	cmp -l vprintf/stdarg.h $inc

pento:
		-mount /pen
		-cmptree -sg . /pen$libc/$DIR
		-forldiff /pen$libc/$DIR
		-rm -f garfield
		-umount /pen

penfrom:
		-mount /pen
		cd /pen$libc/$DIR &&		\
		cmptree -sg . $libc/$DIR;	\
		forldiff $libc/$DIR;		\
		rm -f /pen$libc/$DIR/garfield
		-umount /pen

pensave:
		-mount /pen
		-pento $libc/$DIR
		-umount /pen
