#*
#****************************************************************
#*	Makefile para a biblioteca "libxti"			*
#****************************************************************
#*
man_exec = DUMMY
.putenv man_exec

.virtual	libxti n lint cp cmp man lib clean rmobj

libxti:
	-cd t_accept;		make
	-cd t_addr_to_name;	make
	-cd t_addr_to_node;	make
	-cd t_addr_to_str;	make
	-cd t_alloc;		make
	-cd t_bind;		make
	-cd t_connect;		make
	-cd t_free;		make
	-cd t_getaddr;		make
	-cd t_getinfo;		make
	-cd t_getstate;		make
	-cd t_node_to_addr;	make
	-cd t_listen;		make
	-cd t_look;		make
	-cd t_mail_to_node;	make
	-cd t_nread;		make
	-cd t_open;		make
	-cd t_optmgmt;		make
	-cd t_push;		make
	-cd t_rcv;		make
	-cd t_rcvconnect;	make
	-cd t_rcvdis;		make
	-cd t_rcvraw;		make
	-cd t_rcvrel;		make
	-cd t_rcvudata;		make
	-cd t_rcvuderr;		make
	-cd t_snd;		make
	-cd t_snddis;		make
	-cd t_sndraw;		make
	-cd t_sndrel;		make
	-cd t_sndudata;		make
	-cd t_str_to_addr;	make
	-cd t_strevent;		make
	-cd t_sync;		make
	-cd t_unbind;		make

n:
	-cd t_accept;		make -n
	-cd t_addr_to_name;	make -n
	-cd t_addr_to_node;	make -n
	-cd t_addr_to_str;	make -n
	-cd t_alloc;		make -n
	-cd t_bind;		make -n
	-cd t_connect;		make -n
	-cd t_free;		make -n
	-cd t_getaddr;		make -n
	-cd t_getinfo;		make -n
	-cd t_getstate;		make -n
	-cd t_node_to_addr;	make -n
	-cd t_listen;		make -n
	-cd t_look;		make -n
	-cd t_mail_to_node;	make -n
	-cd t_nread;		make -n
	-cd t_open;		make -n
	-cd t_optmgmt;		make -n
	-cd t_push;		make -n
	-cd t_rcv;		make -n
	-cd t_rcvconnect;	make -n
	-cd t_rcvdis;		make -n
	-cd t_rcvraw;		make -n
	-cd t_rcvrel;		make -n
	-cd t_rcvudata;		make -n
	-cd t_rcvuderr;		make -n
	-cd t_snd;		make -n
	-cd t_snddis;		make -n
	-cd t_sndraw;		make -n
	-cd t_sndrel;		make -n
	-cd t_sndudata;		make -n
	-cd t_str_to_addr;	make -n
	-cd t_strevent;		make -n
	-cd t_sync;		make -n
	-cd t_unbind;		make -n

lint:
	-cd t_accept;		make lint
	-cd t_addr_to_name;	make lint
	-cd t_addr_to_node;	make lint
	-cd t_addr_to_str;	make lint
	-cd t_alloc;		make lint
	-cd t_bind;		make lint
	-cd t_connect;		make lint
	-cd t_free;		make lint
	-cd t_getaddr;		make lint
	-cd t_getinfo;		make lint
	-cd t_getstate;		make lint
	-cd t_node_to_addr;	make lint
	-cd t_listen;		make lint
	-cd t_look;		make lint
	-cd t_mail_to_node;	make lint
	-cd t_nread;		make lint
	-cd t_open;		make lint
	-cd t_optmgmt;		make lint
	-cd t_push;		make lint
	-cd t_rcv;		make lint
	-cd t_rcvconnect;	make lint
	-cd t_rcvdis;		make lint
	-cd t_rcvraw;		make lint
	-cd t_rcvrel;		make lint
	-cd t_rcvudata;		make lint
	-cd t_rcvuderr;		make lint
	-cd t_snd;		make lint
	-cd t_snddis;		make lint
	-cd t_sndraw;		make lint
	-cd t_sndrel;		make lint
	-cd t_sndudata;		make lint
	-cd t_str_to_addr;	make lint
	-cd t_strevent;		make lint
	-cd t_sync;		make lint
	-cd t_unbind;		make lint

cp:
	-mkdir /lib/libxti
	-cd t_accept;		make cp
	-cd t_addr_to_name;	make cp
	-cd t_addr_to_node;	make cp
	-cd t_addr_to_str;	make cp
	-cd t_alloc;		make cp
	-cd t_bind;		make cp
	-cd t_connect;		make cp
	-cd t_free;		make cp
	-cd t_getaddr;		make cp
	-cd t_getinfo;		make cp
	-cd t_getstate;		make cp
	-cd t_node_to_addr;	make cp
	-cd t_listen;		make cp
	-cd t_look;		make cp
	-cd t_mail_to_node;	make cp
	-cd t_nread;		make cp
	-cd t_open;		make cp
	-cd t_optmgmt;		make cp
	-cd t_push;		make cp
	-cd t_rcv;		make cp
	-cd t_rcvconnect;	make cp
	-cd t_rcvdis;		make cp
	-cd t_rcvraw;		make cp
	-cd t_rcvrel;		make cp
	-cd t_rcvudata;		make cp
	-cd t_rcvuderr;		make cp
	-cd t_snd;		make cp
	-cd t_snddis;		make cp
	-cd t_sndraw;		make cp
	-cd t_sndrel;		make cp
	-cd t_sndudata;		make cp
	-cd t_str_to_addr;	make cp
	-cd t_strevent;		make cp
	-cd t_sync;		make cp
	-cd t_unbind;		make cp
	-mklib /lib/libxti

cmp:
	-cd t_accept;		make cmp
	-cd t_addr_to_name;	make cmp
	-cd t_addr_to_node;	make cmp
	-cd t_addr_to_str;	make cmp
	-cd t_alloc;		make cmp
	-cd t_bind;		make cmp
	-cd t_connect;		make cmp
	-cd t_free;		make cmp
	-cd t_getaddr;		make cmp
	-cd t_getinfo;		make cmp
	-cd t_getstate;		make cmp
	-cd t_node_to_addr;	make cmp
	-cd t_listen;		make cmp
	-cd t_look;		make cmp
	-cd t_mail_to_node;	make cmp
	-cd t_nread;		make cmp
	-cd t_open;		make cmp
	-cd t_optmgmt;		make cmp
	-cd t_push;		make cmp
	-cd t_rcv;		make cmp
	-cd t_rcvconnect;	make cmp
	-cd t_rcvdis;		make cmp
	-cd t_rcvraw;		make cmp
	-cd t_rcvrel;		make cmp
	-cd t_rcvudata;		make cmp
	-cd t_rcvuderr;		make cmp
	-cd t_snd;		make cmp
	-cd t_snddis;		make cmp
	-cd t_sndraw;		make cmp
	-cd t_sndrel;		make cmp
	-cd t_sndudata;		make cmp
	-cd t_str_to_addr;	make cmp
	-cd t_strevent;		make cmp
	-cd t_sync;		make cmp
	-cd t_unbind;		make cmp
	-mklib -k /lib/libxti

man:
	-cd t_intro;		make man
	-cd t_accept;		make man
	-cd t_addr_to_name;	make man
	-cd t_addr_to_node;	make man
	-cd t_addr_to_str;	make man
	-cd t_alloc;		make man
	-cd t_bind;		make man
	-cd t_close;		make man
	-cd t_connect;		make man
	-cd t_error;		make man
	-cd t_free;		make man
	-cd t_getaddr;		make man
	-cd t_getinfo;		make man
	-cd t_getstate;		make man
	-cd t_node_to_addr;	make man
	-cd t_listen;		make man
	-cd t_look;		make man
	-cd t_mail_to_node;	make man
	-cd t_nread;		make man
	-cd t_open;		make man
	-cd t_optmgmt;		make man
	-cd t_push;		make man
	-cd t_rcv;		make man
	-cd t_rcvconnect;	make man
	-cd t_rcvdis;		make man
	-cd t_rcvraw;		make man
	-cd t_rcvrel;		make man
	-cd t_rcvudata;		make man
	-cd t_rcvuderr;		make man
	-cd t_snd;		make man
	-cd t_snddis;		make man
	-cd t_sndraw;		make man
	-cd t_sndrel;		make man
	-cd t_sndudata;		make man
	-cd t_str_to_addr;	make man
	-cd t_strevent;		make man
	-cd t_sync;		make man
	-cd t_unbind;		make man

lib:
	mklib /lib/libxti

clean:
	walk -p "*/?.o */? *bobo *garfield" . | rm -iN

rmobj:
	walk -p "*.o" . | rm
