  add_optab->handlers[(int) DImode].lib_call = "__adddi3";
  sub_optab->handlers[(int) DImode].lib_call = "__subdi3";
  smul_optab->handlers[(int) DImode].lib_call = "__muldi3";
  umul_optab->handlers[(int) DImode].lib_call = "__umuldi3";	*********
  sdiv_optab->handlers[(int) DImode].lib_call = "__divdi3";
  udiv_optab->handlers[(int) DImode].lib_call = "__udivdi3";
  smod_optab->handlers[(int) DImode].lib_call = "__moddi3";
  umod_optab->handlers[(int) DImode].lib_call = "__umoddi3";
  flodiv_optab->handlers[(int) DFmode].lib_call = "__divdf3";	*********
  and_optab->handlers[(int) DImode].lib_call = "__anddi3";	*********
  andcb_optab->handlers[(int) DImode].lib_call = "__andcbdi3";	*********
  ior_optab->handlers[(int) DImode].lib_call = "__iordi3";
  xor_optab->handlers[(int) DImode].lib_call = "__xordi3";	*********
  ashl_optab->handlers[(int) DImode].lib_call = "__ashldi3";
  ashr_optab->handlers[(int) DImode].lib_call = "__ashrdi3";
  lshl_optab->handlers[(int) DImode].lib_call = "__lshldi3";
  lshr_optab->handlers[(int) DImode].lib_call = "__lshrdi3";
  rotl_optab->handlers[(int) DImode].lib_call = "__rotldi3";	*********
  rotr_optab->handlers[(int) DImode].lib_call = "__rotrdi3";	*********
  neg_optab->handlers[(int) DImode].lib_call = "__negdi2";
  one_cmpl_optab->handlers[(int) DImode].lib_call = "__one_cmpldi2";	*********
  cmp_optab->handlers[(int) DImode].lib_call = "__cmpdi2";
  ucmp_optab->handlers[(int) DImode].lib_call = "__ucmpdi2";
