#*
#****************************************************************
#*	Makefile para a biblioteca "crt"			*
#****************************************************************
#*
MAC	 = pc
man_exec = DUMMY

.putenv man_exec

.virtual	crt n cp cmp man clr

crt:
	cd addq/$MAC;		make
	cd aldiv/$MAC;		make
	cd almul/$MAC;		make
	cd alrem/$MAC;		make
	cd ashrq/$MAC;		make
	cd auldiv/$MAC;		make
	cd aulmul/$MAC;		make
	cd aulrem/$MAC;		make
	cd cmpsq/$MAC;		make
	cd cmpuq/$MAC;		make
	cd crt0/$MAC;		make
	cd crt1/$MAC;		make
	cd div/$MAC;		make
	cd divmoduq/$MAC;	make
	cd divsq/$MAC;		make
	cd divuq/$MAC;		make
	cd fix/$MAC;		make
	cd ldiv/$MAC;		make
	cd lmul/$MAC;		make
	cd lrem/$MAC;		make
	cd lshlq/$MAC;		make
	cd lshrq/$MAC;		make
	cd modsq/$MAC;		make
	cd moduq/$MAC;		make
	cd muluq/$MAC;		make
	cd negq/$MAC;		make
	cd orq/$MAC;		make
	cd subq/$MAC;		make
	cd uldiv/$MAC;		make
	cd ulmul/$MAC;		make
	cd ulrem/$MAC;		make

n:
	cd addq/$MAC;		make -n
	cd aldiv/$MAC;		make -n
	cd almul/$MAC;		make -n
	cd alrem/$MAC;		make -n
	cd ashrq/$MAC;		make -n
	cd auldiv/$MAC;		make -n
	cd aulmul/$MAC;		make -n
	cd aulrem/$MAC;		make -n
	cd cmpsq/$MAC;		make -n
	cd cmpuq/$MAC;		make -n
	cd crt0/$MAC;		make -n
	cd crt1/$MAC;		make -n
	cd div/$MAC;		make -n
	cd divmoduq/$MAC;	make -n
	cd divsq/$MAC;		make -n
	cd divuq/$MAC;		make -n
	cd fix/$MAC;		make -n
	cd ldiv/$MAC;		make -n
	cd lmul/$MAC;		make -n
	cd lrem/$MAC;		make -n
	cd lshlq/$MAC;		make -n
	cd lshrq/$MAC;		make -n
	cd modsq/$MAC;		make -n
	cd moduq/$MAC;		make -n
	cd muluq/$MAC;		make -n
	cd negq/$MAC;		make -n
	cd orq/$MAC;		make -n
	cd subq/$MAC;		make -n
	cd uldiv/$MAC;		make -n
	cd ulmul/$MAC;		make -n
	cd ulrem/$MAC;		make -n

cp:
	cd addq/$MAC;		make cp
	cd aldiv/$MAC;		make cp
	cd almul/$MAC;		make cp
	cd alrem/$MAC;		make cp
	cd ashrq/$MAC;		make cp
	cd auldiv/$MAC;		make cp
	cd aulmul/$MAC;		make cp
	cd aulrem/$MAC;		make cp
	cd cmpsq/$MAC;		make cp
	cd cmpuq/$MAC;		make cp
	cd crt0/$MAC;		make cp
	cd crt1/$MAC;		make cp
	cd div/$MAC;		make cp
	cd divmoduq/$MAC;	make cp
	cd divsq/$MAC;		make cp
	cd divuq/$MAC;		make cp
#	cd fix/$MAC;		make cp
	cd ldiv/$MAC;		make cp
	cd lmul/$MAC;		make cp
	cd lrem/$MAC;		make cp
	cd lshlq/$MAC;		make cp
	cd lshrq/$MAC;		make cp
	cd modsq/$MAC;		make cp
	cd moduq/$MAC;		make cp
	cd muluq/$MAC;		make cp
	cd negq/$MAC;		make cp
	cd orq/$MAC;		make cp
	cd subq/$MAC;		make cp
	cd uldiv/$MAC;		make cp
	cd ulmul/$MAC;		make cp
	cd ulrem/$MAC;		make cp

cmp:
	cd addq/$MAC;		make cmp
	cd aldiv/$MAC;		make cmp
	cd almul/$MAC;		make cmp
	cd alrem/$MAC;		make cmp
	cd ashrq/$MAC;		make cmp
	cd auldiv/$MAC;		make cmp
	cd aulmul/$MAC;		make cmp
	cd aulrem/$MAC;		make cmp
	cd cmpsq/$MAC;		make cmp
	cd cmpuq/$MAC;		make cmp
	cd crt0/$MAC;		make cmp
	cd crt1/$MAC;		make cmp
	cd div/$MAC;		make cmp
	cd divmoduq/$MAC;	make cmp
	cd divsq/$MAC;		make cmp
	cd divuq/$MAC;		make cmp
#	cd fix/$MAC;		make cmp
	cd ldiv/$MAC;		make cmp
	cd lmul/$MAC;		make cmp
	cd lrem/$MAC;		make cmp
	cd lshlq/$MAC;		make cmp
	cd lshrq/$MAC;		make cmp
	cd modsq/$MAC;		make cmp
	cd moduq/$MAC;		make cmp
	cd muluq/$MAC;		make cmp
	cd negq/$MAC;		make cmp
	cd orq/$MAC;		make cmp
	cd subq/$MAC;		make cmp
	cd uldiv/$MAC;		make cmp
	cd ulmul/$MAC;		make cmp
	cd ulrem/$MAC;		make cmp

man:
	cd crt0/$MAC;	make man
	cd div/$MAC;	make man

clr:
	walk -p "*/?.o */? *bobo *garfield" . | rm -iN
