#*
#****************************************************************
#*	Makefile para a "libc/etc"				*
#****************************************************************
#*
man_exec = DUMMY
MAC	 = pc

.putenv	man_exec

.virtual	etc n lint cp cmp cmpqcp man clr gar
.virtual	pento penfrom pensave

etc:
	cd abort;	make
	cd abs/$MAC;	make
	cd askyesno;	make
	cd assert;	make
	cd atexit;	make
	cd bsearch;	make
	cd clock;	make
	cd crc16;	make
	cd crc16s;	make
	cd crypt;	make
	cd ctime;	make
	cd ctype;	make
	cd delenv;	make
	cd dirent;	make
	cd edit;	make
#	cd end;		make
	cd endian/$MAC;	make
	cd error;	make
	cd execvp;	make
	cd ffbs;	make
	cd ftw;		make
	cd getcwd;	make
	cd getenv;	make
	cd getmntent;	make
	cd getopt;	make
	cd getrand/$MAC;make
	cd initent;	make
	cd isatty;	make
	cd l3tol;	make
	cd locale;	make
	cd localtime;	make
	cd mkasmtb;	make
	cd mktemp;	make
	cd mktime;	make
	cd modecolor;	make
	cd modetostr;	make
	cd nlist;	make
	cd patmatch;	make
	cd perror;	make
	cd putenv;	make
	cd qsort;	make
	cd qtsort;	make
	cd raise;	make
	cd rand;	make
	cd regcmp;	make
	cd remove;	make
#	cd rename;	make
	cd setjmp/$MAC;	make
	cd sigtostr;	make
	cd sleep;	make
	cd strftime;	make
	cd strtotime;	make
	cd system;	make
	cd tmpfile;	make
	cd tmpnam;	make
	cd ttyname;	make
#	cd ttyslot;	make

n:
	cd abort;	make -n
	cd abs/$MAC;	make -n
	cd askyesno;	make -n
	cd assert;	make -n
	cd atexit;	make -n
	cd bsearch;	make -n
	cd clock;	make -n
	cd crc16;	make -n
	cd crc16s;	make -n
	cd crypt;	make -n
	cd ctime;	make -n
	cd ctype;	make -n
	cd delenv;	make -n
	cd dirent;	make -n
	cd edit;	make -n
#	cd end;		make -n
	cd endian/$MAC;	make -n
	cd error;	make -n
	cd execvp;	make -n
	cd ffbs;	make -n
	cd ftw;		make -n
	cd getcwd;	make -n
	cd getenv;	make -n
	cd getmntent;	make -n
	cd getopt;	make -n
	cd getrand/$MAC;make -n
	cd initent;	make -n
	cd isatty;	make -n
	cd l3tol;	make -n
	cd locale;	make -n
	cd localtime;	make -n
	cd mkasmtb;	make -n
	cd mktemp;	make -n
	cd mktime;	make -n
	cd modecolor;	make -n
	cd modetostr;	make -n
	cd nlist;	make -n
	cd patmatch;	make -n
	cd perror;	make -n
	cd putenv;	make -n
	cd qsort;	make -n
	cd qtsort;	make -n
	cd raise;	make -n
	cd rand;	make -n
	cd regcmp;	make -n
	cd remove;	make -n
#	cd rename;	make -n
	cd setjmp/$MAC;	make -n
	cd sigtostr;	make -n
	cd sleep;	make -n
	cd strftime;	make -n
	cd strtotime;	make -n
	cd system;	make -n
	cd tmpfile;	make -n
	cd tmpnam;	make -n
	cd ttyname;	make -n
#	cd ttyslot;	make -n

lint:
	cd abort;	make lint
#	cd abs/$MAC;	make lint
	cd askyesno;	make lint
	cd assert;	make lint
	cd atexit;	make lint
	cd bsearch;	make lint
	cd clock;	make lint
	cd crc16;	make lint
	cd crc16s;	make lint
	cd crypt;	make lint
	cd ctime;	make lint
	cd ctype;	make lint
	cd delenv;	make lint
	cd dirent;	make lint
	cd edit;	make lint
#	cd end;		make lint
#	cd endian/$MAC;	make lint
	cd error;	make lint
	cd execvp;	make lint
#	cd ffbs;	make lint
	cd ftw;		make lint
	cd getcwd;	make lint
	cd getenv;	make lint
	cd getmntent;	make lint
	cd getopt;	make lint
#	cd getrand/$MAC;make lint
	cd initent;	make lint
	cd isatty;	make lint
	cd l3tol;	make lint
	cd locale;	make lint
	cd localtime;	make lint
	cd mkasmtb;	make lint
	cd mktemp;	make lint
	cd mktime;	make lint
	cd modecolor;	make lint
	cd modetostr;	make lint
	cd nlist;	make lint
	cd patmatch;	make lint
	cd perror;	make lint
	cd putenv;	make lint
	cd qsort;	make lint
	cd qtsort;	make lint
	cd raise;	make lint
	cd rand;	make lint
	cd regcmp;	make lint
	cd remove;	make lint
#	cd rename;	make lint
#	cd setjmp/$MAC;	make lint
	cd sigtostr;	make lint
	cd sleep;	make lint
	cd strftime;	make lint
	cd strtotime;	make lint
	cd system;	make lint
	cd tmpfile;	make lint
	cd tmpnam;	make lint
	cd ttyname;	make lint
#	cd ttyslot;	make lint

cp:
	cd abort;	make cp
	cd abs/$MAC;	make cp
	cd askyesno;	make cp
	cd assert;	make cp
	cd atexit;	make cp
	cd bsearch;	make cp
	cd clock;	make cp
	cd crc16;	make cp
	cd crc16s;	make cp
	cd crypt;	make cp
	cd ctime;	make cp
	cd ctype;	make cp
	cd delenv;	make cp
	cd dirent;	make cp
	cd edit;	make cp
#	cd end;		make cp
	cd endian/$MAC;	make cp
	cd error;	make cp
	cd execvp;	make cp
	cd ffbs;	make cp
	cd ftw;		make cp
	cd getcwd;	make cp
	cd getenv;	make cp
	cd getmntent;	make cp
	cd getopt;	make cp
	cd getrand/$MAC;make cp
	cd initent;	make cp
	cd isatty;	make cp
	cd l3tol;	make cp
	cd locale;	make cp
	cd localtime;	make cp
	cd mkasmtb;	make cp
	cd mktemp;	make cp
	cd mktime;	make cp
	cd modecolor;	make cp
	cd modetostr;	make cp
	cd nlist;	make cp
	cd patmatch;	make cp
	cd perror;	make cp
	cd putenv;	make cp
	cd qsort;	make cp
	cd qtsort;	make cp
	cd raise;	make cp
	cd rand;	make cp
	cd regcmp;	make cp
	cd remove;	make cp
#	cd rename;	make cp
	cd setjmp/$MAC;	make cp
	cd sigtostr;	make cp
	cd sleep;	make cp
	cd strftime;	make cp
	cd strtotime;	make cp
	cd system;	make cp
	cd tmpfile;	make cp
	cd tmpnam;	make cp
	cd ttyname;	make cp
#	cd ttyslot;	make cp

cmp:
	cd abort;	make cmp
	cd abs/$MAC;	make cmp
	cd askyesno;	make cmp
	cd assert;	make cmp
	cd atexit;	make cmp
	cd bsearch;	make cmp
	cd clock;	make cmp
	cd crc16;	make cmp
	cd crc16s;	make cmp
	cd crypt;	make cmp
	cd ctime;	make cmp
	cd ctype;	make cmp
	cd delenv;	make cmp
	cd dirent;	make cmp
	cd edit;	make cmp
#	cd end;		make cmp
	cd endian/$MAC;	make cmp
	cd error;	make cmp
	cd execvp;	make cmp
	cd ffbs;	make cmp
	cd ftw;		make cmp
	cd getcwd;	make cmp
	cd getenv;	make cmp
	cd getmntent;	make cmp
	cd getopt;	make cmp
	cd getrand/$MAC;make cmp
	cd initent;	make cmp
	cd isatty;	make cmp
	cd l3tol;	make cmp
	cd locale;	make cmp
	cd localtime;	make cmp
	cd mkasmtb;	make cmp
	cd mktemp;	make cmp
	cd mktime;	make cmp
	cd modecolor;	make cmp
	cd modetostr;	make cmp
	cd nlist;	make cmp
	cd patmatch;	make cmp
	cd perror;	make cmp
	cd putenv;	make cmp
	cd qsort;	make cmp
	cd qtsort;	make cmp
	cd raise;	make cmp
	cd rand;	make cmp
	cd regcmp;	make cmp
	cd remove;	make cmp
#	cd rename;	make cmp
	cd setjmp/$MAC;	make cmp
	cd sigtostr;	make cmp
	cd sleep;	make cmp
	cd strftime;	make cmp
	cd strtotime;	make cmp
	cd system;	make cmp
	cd tmpfile;	make cmp
	cd tmpnam;	make cmp
	cd ttyname;	make cmp
#	cd ttyslot;	make cmp

cmpqcp:
	cd abort;	make cmpqcp
	cd abs/$MAC;	make cmpqcp
	cd askyesno;	make cmpqcp
	cd assert;	make cmpqcp
	cd atexit;	make cmpqcp
	cd bsearch;	make cmpqcp
	cd clock;	make cmpqcp
	cd crc16;	make cmpqcp
	cd crc16s;	make cmpqcp
	cd crypt;	make cmpqcp
	cd ctime;	make cmpqcp
	cd ctype;	make cmpqcp
	cd delenv;	make cmpqcp
	cd dirent;	make cmpqcp
	cd edit;	make cmpqcp
#	cd end;		make cmpqcp
	cd endian/$MAC;	make cmpqcp
	cd error;	make cmpqcp
	cd execvp;	make cmpqcp
	cd ffbs;	make cmpqcp
	cd ftw;		make cmpqcp
	cd getcwd;	make cmpqcp
	cd getenv;	make cmpqcp
	cd getmntent;	make cmpqcp
	cd getopt;	make cmpqcp
	cd getrand/$MAC;make cmpqcp
	cd initent;	make cmpqcp
	cd isatty;	make cmpqcp
	cd l3tol;	make cmpqcp
	cd locale;	make cmpqcp
	cd localtime;	make cmpqcp
	cd mkasmtb;	make cmpqcp
	cd mktemp;	make cmpqcp
	cd mktime;	make cmpqcp
	cd modecolor;	make cmpqcp
	cd modetostr;	make cmpqcp
	cd nlist;	make cmpqcp
	cd patmatch;	make cmpqcp
	cd perror;	make cmpqcp
	cd putenv;	make cmpqcp
	cd qsort;	make cmpqcp
	cd qtsort;	make cmpqcp
	cd raise;	make cmpqcp
	cd rand;	make cmpqcp
	cd regcmp;	make cmpqcp
	cd remove;	make cmpqcp
#	cd rename;	make cmpqcp
	cd setjmp/$MAC;	make cmpqcp
	cd sigtostr;	make cmpqcp
	cd sleep;	make cmpqcp
	cd strftime;	make cmpqcp
	cd strtotime;	make cmpqcp
	cd system;	make cmpqcp
	cd tmpfile;	make cmpqcp
	cd tmpnam;	make cmpqcp
	cd ttyname;	make cmpqcp
#	cd ttyslot;	make cmpqcp

man:
	cd abort;	make man
	cd abs/$MAC;	make man
	cd askyesno;	make man
	cd assert;	make man
	cd atexit;	make man
	cd bsearch;	make man
	cd clock;	make man
	cd crc16;	make man
	cd crc16s;	make man
	cd crypt;	make man
	cd ctime;	make man
	cd ctype;	make man
	cd delenv;	make man
	cd dirent;	make man
	cd edit;	make man
	cd end;		make man
	cd endian/$MAC;	make man
	cd error;	make man
	cd execvp;	make man
	cd ffbs;	make man
	cd ftw;		make man
	cd getcwd;	make man
	cd getenv;	make man
	cd getmntent;	make man
	cd getopt;	make man
	cd getrand/$MAC;make man
	cd initent;	make man
	cd isatty;	make man
	cd l3tol;	make man
	cd locale;	make man
	cd localtime;	make man
	cd mkasmtb;	make man
	cd mktemp;	make man
	cd mktime;	make man
	cd modecolor;	make man
	cd modetostr;	make man
	cd nlist;	make man
	cd patmatch;	make man
	cd perror;	make man
	cd putenv;	make man
	cd qsort;	make man
	cd qtsort;	make man
	cd raise;	make man
	cd rand;	make man
	cd regcmp;	make man
	cd remove;	make man
#	cd rename;	make man
	cd setjmp/$MAC;	make man
	cd sigtostr;	make man
	cd sleep;	make man
	cd strftime;	make man
	cd strtotime;	make man
	cd system;	make man
	cd tmpfile;	make man
	cd tmpnam;	make man
	cd ttyname;	make man
#	cd ttyslot;	make man

clr:
	walk -p "*/?.o */? *bobo *garfield" . | rm -iN

gar:
	cd ..; gar -ovs0 etc
	cd ..; gar -icv0

pento:
		-mount /pen
		-cmptree -sg . /pen$libc/etc
		-forldiff /pen$libc/etc
		-rm -f garfield
		-umount /pen

penfrom:
		-mount /pen
		cd /pen$libc/etc &&		\
		cmptree -sg . $libc/etc;	\
		forldiff $libc/etc;		\
		rm -f /pen$libc/etc/garfield
		-umount /pen

pensave:
		-mount /pen
		-pento $libc/etc
		-umount /pen
