#*
#****************************************************************
#*	Makefile para a bibliteca "sys"				*
#****************************************************************
#*
man_exec = DUMMY
MAC	= pc

.putenv man_exec

.virtual	sys n cp cmp man clr
.virtual	pento penfrom pensave

sys:
	cd access/$MAC;		make
	cd alarm/$MAC;		make
	cd attention/$MAC;	make
	cd boot/$MAC;		make
	cd brk/$MAC;		make
	cd chdir/$MAC;		make
	cd chdirip/$MAC;	make
	cd chmod/$MAC;		make
	cd chown/$MAC;		make
	cd chroot/$MAC;		make
	cd close/$MAC;		make
	cd creat/$MAC;		make
	cd dup/$MAC;		make
	cd event/$MAC;		make
	cd exec/$MAC;		make
	cd exit/$MAC;		make
	cd fcntl/$MAC;		make
	cd fork/$MAC;		make
	cd fstat/$MAC;		make
	cd getdirent/$MAC;	make
	cd getdirpar/$MAC;	make
	cd getegid/$MAC;	make
	cd geteuid/$MAC;	make
	cd getgid/$MAC;		make
	cd getpgrp/$MAC;	make
	cd getpid/$MAC;		make
	cd getppid/$MAC;	make
	cd getpty/$MAC;		make
	cd getscb/$MAC;		make
	cd getsn/$MAC;		make
	cd gettzmin/$MAC;	make
	cd getuid/$MAC;		make
	cd inopen/$MAC;		make
	cd instat/$MAC;		make
#	cd intro;		make
	cd ioctl/$MAC;		make
	cd itnet/$MAC;		make
	cd itnetrcv/$MAC;	make
	cd itnetsnd/$MAC;	make
	cd kcntl/$MAC;		make
	cd kill/$MAC;		make
	cd link/$MAC;		make
	cd lockf/$MAC;		make
	cd lseek/$MAC;		make
	cd llseek/$MAC;		make
	cd lstat/$MAC;		make
	cd mkdir/$MAC;		make
	cd mknod/$MAC;		make
	cd mount/$MAC;		make
	cd mutime/$MAC;		make
	cd mutimes/$MAC;	make
	cd nice/$MAC;		make
	cd open/$MAC;		make
	cd pause/$MAC;		make
	cd pcntl/$MAC;		make
	cd phys/$MAC;		make
	cd pipe/$MAC;		make
	cd plock/$MAC;		make
	cd ptrace/$MAC;		make
	cd read/$MAC;		make
	cd readlink/$MAC;	make
	cd rename/$MAC;		make
	cd rmdir/$MAC;		make
	cd select/$MAC;		make
	cd sema/$MAC;		make
	cd setgid/$MAC;		make
	cd setpgrp/$MAC;	make
	cd setppid/$MAC;	make
	cd setregid/$MAC;	make
	cd setreuid/$MAC;	make
	cd setscb/$MAC;		make
	cd settgrp/$MAC;	make
	cd setuid/$MAC;		make
	cd shlib/$MAC;		make
	cd shmem/$MAC;		make
	cd sigchild/$MAC;	make
	cd signal/$MAC;		make
	cd spy/$MAC;		make
	cd stat/$MAC;		make
	cd stime/$MAC;		make
	cd symlink/$MAC;	make
	cd sync/$MAC;		make
	cd thread/$MAC;		make
	cd time/$MAC;		make
	cd times/$MAC;		make
	cd umask/$MAC;		make
	cd umount/$MAC;		make
	cd uname/$MAC;		make
	cd unlink/$MAC;		make
	cd untext/$MAC;		make
	cd upstat/$MAC;		make
	cd ustat/$MAC;		make
	cd utime/$MAC;		make
	cd wait/$MAC;		make
	cd write/$MAC;		make

n:
	cd access/$MAC;		make -n
	cd alarm/$MAC;		make -n
	cd attention/$MAC;	make -n
	cd boot/$MAC;		make -n
	cd brk/$MAC;		make -n
	cd chdir/$MAC;		make -n
	cd chdirip/$MAC;	make -n
	cd chmod/$MAC;		make -n
	cd chown/$MAC;		make -n
	cd chroot/$MAC;		make -n
	cd close/$MAC;		make -n
	cd creat/$MAC;		make -n
	cd dup/$MAC;		make -n
	cd event/$MAC;		make -n
	cd exec/$MAC;		make -n
	cd exit/$MAC;		make -n
	cd fcntl/$MAC;		make -n
	cd fork/$MAC;		make -n
	cd fstat/$MAC;		make -n
	cd getdirent/$MAC;	make -n
	cd getdirpar/$MAC;	make -n
	cd getegid/$MAC;	make -n
	cd geteuid/$MAC;	make -n
	cd getgid/$MAC;		make -n
	cd getpgrp/$MAC;	make -n
	cd getpid/$MAC;		make -n
	cd getppid/$MAC;	make -n
	cd getpty/$MAC;		make -n
	cd getscb/$MAC;		make -n
	cd getsn/$MAC;		make -n
	cd gettzmin/$MAC;	make -n
	cd getuid/$MAC;		make -n
	cd inopen/$MAC;		make -n
	cd instat/$MAC;		make -n
	cd intro;		make -n
	cd ioctl/$MAC;		make -n
	cd itnet/$MAC;		make -n
	cd itnetrcv/$MAC;	make -n
	cd itnetsnd/$MAC;	make -n
	cd kcntl/$MAC;		make -n
	cd kill/$MAC;		make -n
	cd link/$MAC;		make -n
	cd lockf/$MAC;		make -n
	cd lseek/$MAC;		make -n
	cd llseek/$MAC;		make -n
	cd lstat/$MAC;		make -n
	cd mkdir/$MAC;		make -n
	cd mknod/$MAC;		make -n
	cd mount/$MAC;		make -n
	cd mutime/$MAC;		make -n
	cd mutimes/$MAC;	make -n
	cd nice/$MAC;		make -n
	cd open/$MAC;		make -n
	cd pause/$MAC;		make -n
	cd pcntl/$MAC;		make -n
	cd phys/$MAC;		make -n
	cd pipe/$MAC;		make -n
	cd plock/$MAC;		make -n
	cd ptrace/$MAC;		make -n
	cd read/$MAC;		make -n
	cd readlink/$MAC;	make -n
	cd rename/$MAC;		make -n
	cd rmdir/$MAC;		make -n
	cd select/$MAC;		make -n
	cd sema/$MAC;		make -n
	cd setgid/$MAC;		make -n
	cd setpgrp/$MAC;	make -n
	cd setppid/$MAC;	make -n
	cd setregid/$MAC;	make -n
	cd setreuid/$MAC;	make -n
	cd setscb/$MAC;		make -n
	cd settgrp/$MAC;	make -n
	cd setuid/$MAC;		make -n
	cd shlib/$MAC;		make -n
	cd shmem/$MAC;		make -n
	cd sigchild/$MAC;	make -n
	cd signal/$MAC;		make -n
	cd spy/$MAC;		make -n
	cd stat/$MAC;		make -n
	cd stime/$MAC;		make -n
	cd symlink/$MAC;	make -n
	cd sync/$MAC;		make -n
	cd thread/$MAC;		make -n
	cd time/$MAC;		make -n
	cd times/$MAC;		make -n
	cd umask/$MAC;		make -n
	cd umount/$MAC;		make -n
	cd uname/$MAC;		make -n
	cd unlink/$MAC;		make -n
	cd untext/$MAC;		make -n
	cd upstat/$MAC;		make -n
	cd ustat/$MAC;		make -n
	cd utime/$MAC;		make -n
	cd wait/$MAC;		make -n
	cd write/$MAC;		make -n

cp:
	cd access/$MAC;		make cp
	cd alarm/$MAC;		make cp
	cd attention/$MAC;	make cp
	cd boot/$MAC;		make cp
	cd brk/$MAC;		make cp
	cd chdir/$MAC;		make cp
	cd chdirip/$MAC;	make cp
	cd chmod/$MAC;		make cp
	cd chown/$MAC;		make cp
	cd chroot/$MAC;		make cp
	cd close/$MAC;		make cp
	cd creat/$MAC;		make cp
	cd dup/$MAC;		make cp
	cd event/$MAC;		make cp
	cd exec/$MAC;		make cp
	cd exit/$MAC;		make cp
	cd fcntl/$MAC;		make cp
	cd fork/$MAC;		make cp
	cd fstat/$MAC;		make cp
	cd getdirent/$MAC;	make cp
	cd getdirpar/$MAC;	make cp
	cd getegid/$MAC;	make cp
	cd geteuid/$MAC;	make cp
	cd getgid/$MAC;		make cp
	cd getpgrp/$MAC;	make cp
	cd getpid/$MAC;		make cp
	cd getppid/$MAC;	make cp
	cd getpty/$MAC;		make cp
	cd getscb/$MAC;		make cp
	cd getsn/$MAC;		make cp
	cd gettzmin/$MAC;	make cp
	cd getuid/$MAC;		make cp
	cd inopen/$MAC;		make cp
	cd instat/$MAC;		make cp
#	cd intro;		make cp
	cd ioctl/$MAC;		make cp
	cd itnet/$MAC;		make cp
	cd itnetrcv/$MAC;	make cp
	cd itnetsnd/$MAC;	make cp
	cd kcntl/$MAC;		make cp
	cd kill/$MAC;		make cp
	cd link/$MAC;		make cp
	cd lockf/$MAC;		make cp
	cd lseek/$MAC;		make cp
	cd llseek/$MAC;		make cp
	cd lstat/$MAC;		make cp
	cd mkdir/$MAC;		make cp
	cd mknod/$MAC;		make cp
	cd mount/$MAC;		make cp
	cd mutime/$MAC;		make cp
	cd mutimes/$MAC;	make cp
	cd nice/$MAC;		make cp
	cd open/$MAC;		make cp
	cd pause/$MAC;		make cp
	cd pcntl/$MAC;		make cp
	cd phys/$MAC;		make cp
	cd pipe/$MAC;		make cp
	cd plock/$MAC;		make cp
	cd ptrace/$MAC;		make cp
	cd read/$MAC;		make cp
	cd readlink/$MAC;	make cp
	cd rename/$MAC;		make cp
	cd rmdir/$MAC;		make cp
	cd select/$MAC;		make cp
	cd sema/$MAC;		make cp
	cd setgid/$MAC;		make cp
	cd setpgrp/$MAC;	make cp
	cd setppid/$MAC;	make cp
	cd setregid/$MAC;	make cp
	cd setreuid/$MAC;	make cp
	cd setscb/$MAC;		make cp
	cd settgrp/$MAC;	make cp
	cd setuid/$MAC;		make cp
	cd shlib/$MAC;		make cp
	cd shmem/$MAC;		make cp
	cd sigchild/$MAC;	make cp
	cd signal/$MAC;		make cp
	cd spy/$MAC;		make cp
	cd stat/$MAC;		make cp
	cd stime/$MAC;		make cp
	cd symlink/$MAC;	make cp
	cd sync/$MAC;		make cp
	cd thread/$MAC;		make cp
	cd time/$MAC;		make cp
	cd times/$MAC;		make cp
	cd umask/$MAC;		make cp
	cd umount/$MAC;		make cp
	cd uname/$MAC;		make cp
	cd unlink/$MAC;		make cp
	cd untext/$MAC;		make cp
	cd upstat/$MAC;		make cp
	cd ustat/$MAC;		make cp
	cd utime/$MAC;		make cp
	cd wait/$MAC;		make cp
	cd write/$MAC;		make cp

cmp:
	cd access/$MAC;		make cmp
	cd alarm/$MAC;		make cmp
	cd attention/$MAC;	make cmp
	cd boot/$MAC;		make cmp
	cd brk/$MAC;		make cmp
	cd chdir/$MAC;		make cmp
	cd chdirip/$MAC;	make cmp
	cd chmod/$MAC;		make cmp
	cd chown/$MAC;		make cmp
	cd chroot/$MAC;		make cmp
	cd close/$MAC;		make cmp
	cd creat/$MAC;		make cmp
	cd dup/$MAC;		make cmp
	cd event/$MAC;		make cmp
	cd exec/$MAC;		make cmp
	cd exit/$MAC;		make cmp
	cd fcntl/$MAC;		make cmp
	cd fork/$MAC;		make cmp
	cd fstat/$MAC;		make cmp
	cd getdirent/$MAC;	make cmp
	cd getdirpar/$MAC;	make cmp
	cd getegid/$MAC;	make cmp
	cd geteuid/$MAC;	make cmp
	cd getgid/$MAC;		make cmp
	cd getpgrp/$MAC;	make cmp
	cd getpid/$MAC;		make cmp
	cd getppid/$MAC;	make cmp
	cd getpty/$MAC;		make cmp
	cd getscb/$MAC;		make cmp
	cd getsn/$MAC;		make cmp
	cd gettzmin/$MAC;	make cmp
	cd getuid/$MAC;		make cmp
	cd inopen/$MAC;		make cmp
	cd instat/$MAC;		make cmp
#	cd intro;		make cmp
	cd ioctl/$MAC;		make cmp
	cd itnet/$MAC;		make cmp
	cd itnetrcv/$MAC;	make cmp
	cd itnetsnd/$MAC;	make cmp
	cd kcntl/$MAC;		make cmp
	cd kill/$MAC;		make cmp
	cd link/$MAC;		make cmp
	cd lockf/$MAC;		make cmp
	cd lseek/$MAC;		make cmp
	cd llseek/$MAC;		make cmp
	cd lstat/$MAC;		make cmp
	cd mkdir/$MAC;		make cmp
	cd mknod/$MAC;		make cmp
	cd mount/$MAC;		make cmp
	cd mutime/$MAC;		make cmp
	cd mutimes/$MAC;	make cmp
	cd nice/$MAC;		make cmp
	cd open/$MAC;		make cmp
	cd pause/$MAC;		make cmp
	cd pcntl/$MAC;		make cmp
	cd phys/$MAC;		make cmp
	cd pipe/$MAC;		make cmp
	cd plock/$MAC;		make cmp
	cd ptrace/$MAC;		make cmp
	cd read/$MAC;		make cmp
	cd readlink/$MAC;	make cmp
	cd rename/$MAC;		make cmp
	cd rmdir/$MAC;		make cmp
	cd select/$MAC;		make cmp
	cd sema/$MAC;		make cmp
	cd setgid/$MAC;		make cmp
	cd setpgrp/$MAC;	make cmp
	cd setppid/$MAC;	make cmp
	cd setregid/$MAC;	make cmp
	cd setreuid/$MAC;	make cmp
	cd setscb/$MAC;		make cmp
	cd settgrp/$MAC;	make cmp
	cd setuid/$MAC;		make cmp
	cd shlib/$MAC;		make cmp
	cd shmem/$MAC;		make cmp
	cd sigchild/$MAC;	make cmp
	cd signal/$MAC;		make cmp
	cd spy/$MAC;		make cmp
	cd stat/$MAC;		make cmp
	cd stime/$MAC;		make cmp
	cd symlink/$MAC;	make cmp
	cd sync/$MAC;		make cmp
	cd thread/$MAC;		make cmp
	cd time/$MAC;		make cmp
	cd times/$MAC;		make cmp
	cd umask/$MAC;		make cmp
	cd umount/$MAC;		make cmp
	cd uname/$MAC;		make cmp
	cd unlink/$MAC;		make cmp
	cd untext/$MAC;		make cmp
	cd upstat/$MAC;		make cmp
	cd ustat/$MAC;		make cmp
	cd utime/$MAC;		make cmp
	cd wait/$MAC;		make cmp
	cd write/$MAC;		make cmp

man:
	cd access/$MAC;		make man
	cd alarm/$MAC;		make man
	cd attention/$MAC;	make man
	cd boot/$MAC;		make man
	cd brk/$MAC;		make man
	cd chdir/$MAC;		make man
	cd chdirip/$MAC;	make man
	cd chmod/$MAC;		make man
	cd chown/$MAC;		make man
	cd chroot/$MAC;		make man
	cd close/$MAC;		make man
	cd creat/$MAC;		make man
	cd dup/$MAC;		make man
	cd event/$MAC;		make man
	cd exec/$MAC;		make man
	cd exit/$MAC;		make man
	cd fcntl/$MAC;		make man
	cd fork/$MAC;		make man
	cd fstat/$MAC;		make man
	cd getdirent/$MAC;	make man
	cd getdirpar/$MAC;	make man
	cd getegid/$MAC;	make man
	cd geteuid/$MAC;	make man
	cd getgid/$MAC;		make man
	cd getpgrp/$MAC;	make man
	cd getpid/$MAC;		make man
	cd getppid/$MAC;	make man
	cd getpty/$MAC;		make man
	cd getscb/$MAC;		make man
	cd getsn/$MAC;		make man
	cd gettzmin/$MAC;	make man
	cd getuid/$MAC;		make man
	cd inopen/$MAC;		make man
	cd instat/$MAC;		make man
	cd intro;		make man
	cd ioctl/$MAC;		make man
	cd itnet/$MAC;		make man
	cd itnetrcv/$MAC;	make man
	cd itnetsnd/$MAC;	make man
	cd kcntl/$MAC;		make man
	cd kill/$MAC;		make man
	cd link/$MAC;		make man
	cd lockf/$MAC;		make man
	cd lseek/$MAC;		make man
	cd llseek/$MAC;		make man
#	cd lstat/$MAC;		make man
	cd mkdir/$MAC;		make man
	cd mknod/$MAC;		make man
	cd mount/$MAC;		make man
	cd mutime/$MAC;		make man
	cd mutimes/$MAC;	make man
	cd nice/$MAC;		make man
	cd open/$MAC;		make man
	cd pause/$MAC;		make man
	cd pcntl/$MAC;		make man
	cd phys/$MAC;		make man
	cd pipe/$MAC;		make man
	cd plock/$MAC;		make man
	cd ptrace/$MAC;		make man
	cd read/$MAC;		make man
	cd readlink/$MAC;	make man
	cd rename/$MAC;		make man
	cd rmdir/$MAC;		make man
	cd select/$MAC;		make man
	cd sema/$MAC;		make man
	cd setgid/$MAC;		make man
	cd setpgrp/$MAC;	make man
	cd setppid/$MAC;	make man
	cd setregid/$MAC;	make man
	cd setreuid/$MAC;	make man
	cd setscb/$MAC;		make man
	cd settgrp/$MAC;	make man
	cd setuid/$MAC;		make man
	cd shlib/$MAC;		make man
	cd shmem/$MAC;		make man
	cd sigchild/$MAC;	make man
	cd signal/$MAC;		make man
	cd spy/$MAC;		make man
	cd stat/$MAC;		make man
	cd stime/$MAC;		make man
	cd symlink/$MAC;	make man
	cd sync/$MAC;		make man
	cd thread/$MAC;		make man
	cd time/$MAC;		make man
	cd times/$MAC;		make man
	cd umask/$MAC;		make man
	cd umount/$MAC;		make man
	cd uname/$MAC;		make man
	cd unlink/$MAC;		make man
	cd untext/$MAC;		make man
	cd upstat/$MAC;		make man
	cd ustat/$MAC;		make man
	cd utime/$MAC;		make man
	cd wait/$MAC;		make man
	cd write/$MAC;		make man

clr:
	walk -p "*/?.o */? *bobo *garfield" . | rm -iN

gar:
	cd ../$MAC; gar -ovs0 sys
	cd ../$MAC; gar -icv0


pento:
		-mount /pen
		-cmptree -sg . /pen$libc/sys
		-forldiff /pen$libc/sys
		-rm -f garfield
		-umount /pen

penfrom:
		-mount /pen
		cd /pen$libc/sys &&		\
		cmptree -sg . $libc/sys;	\
		forldiff $libc/sys;		\
		rm -f /pen$libc/sys/garfield
		-umount /pen

pensave:
		-mount /pen
		-pento $libc/sys
		-umount /pen
