/* $XFree86: xc/programs/Xserver/os/stdrgb.c,v 1.1 2005/06/22 03:28:51 dawes Exp $ */

/*
 * THIS FILE IS AUTOMATICALLY GENERATED -- DO NOT EDIT
 *
 * It is generated by rgbBuiltin.pl using data from the following file:
 *
 *    ../../rgb/rgb.txt
 *
 * Copyright © 2005 by The XFree86 Project, Inc.
 * All Rights Reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject
 * to the following conditions:
 *
 *   1.  Redistributions of source code must retain the above copyright
 *       notice, this list of conditions, and the following disclaimer.
 *
 *   2.  Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer
 *       in the documentation and/or other materials provided with the
 *       distribution, and in the same place and form as other copyright,
 *       license and disclaimer information.
 *
 *   3.  The end-user documentation included with the redistribution,
 *       if any, must include the following acknowledgment: "This product
 *       includes software developed by The XFree86 Project, Inc
 *       (http://www.xfree86.org/) and its contributors", in the same
 *       place and form as other third-party acknowledgments.  Alternately,
 *       this acknowledgment may appear in the software itself, in the
 *       same form and location as other such third-party acknowledgments.
 *
 *   4.  Except as contained in this notice, the name of The XFree86
 *       Project, Inc shall not be used in advertising or otherwise to
 *       promote the sale, use or other dealings in this Software without
 *       prior written authorization from The XFree86 Project, Inc.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE XFREE86 PROJECT, INC OR ITS CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY,
 * OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
 * OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
 * EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>
#include "oscolor.h"

#define C 0x101

static const char c5_0[] = "pink";
static dbEntry e5_0 = {NULL, 255 * C, 192 * C, 203 * C, c5_0};
static const char c8_0[] = "cadetblue";
static dbEntry e8_0 = {NULL, 95 * C, 158 * C, 160 * C, c8_0};
static const char c14_0[] = "seashell";
static dbEntry e14_0 = {NULL, 255 * C, 245 * C, 238 * C, c14_0};
static const char c16_0[] = "cornflowerblue";
static dbEntry e16_0 = {NULL, 100 * C, 149 * C, 237 * C, c16_0};
static const char c19_0[] = "salmon1";
static dbEntry e19_0 = {NULL, 255 * C, 140 * C, 105 * C, c19_0};
static const char c21_0[] = "antiquewhite4";
static dbEntry e21_0 = {NULL, 139 * C, 131 * C, 120 * C, c21_0};
static const char c21_1[] = "salmon2";
static dbEntry e21_1 = {&e21_0, 238 * C, 130 * C, 98 * C, c21_1};
static const char c21_2[] = "salmon3";
static dbEntry e21_2 = {&e21_1, 205 * C, 112 * C, 84 * C, c21_2};
static const char c22_0[] = "antiquewhite1";
static dbEntry e22_0 = {NULL, 255 * C, 239 * C, 219 * C, c22_0};
static const char c23_0[] = "antiquewhite2";
static dbEntry e23_0 = {NULL, 238 * C, 223 * C, 204 * C, c23_0};
static const char c23_1[] = "salmon4";
static dbEntry e23_1 = {&e23_0, 139 * C, 76 * C, 57 * C, c23_1};
static const char c23_2[] = "darkblue";
static dbEntry e23_2 = {&e23_1, 0 * C, 0 * C, 139 * C, c23_2};
static const char c24_0[] = "antiquewhite3";
static dbEntry e24_0 = {NULL, 205 * C, 192 * C, 176 * C, c24_0};
static const char c26_0[] = "lawngreen";
static dbEntry e26_0 = {NULL, 124 * C, 252 * C, 0 * C, c26_0};
static const char c28_0[] = "lightsteelblue1";
static dbEntry e28_0 = {NULL, 202 * C, 225 * C, 255 * C, c28_0};
static const char c28_1[] = "yellow1";
static dbEntry e28_1 = {&e28_0, 255 * C, 255 * C, 0 * C, c28_1};
static const char c28_2[] = "yellow2";
static dbEntry e28_2 = {&e28_1, 238 * C, 238 * C, 0 * C, c28_2};
static const char c28_3[] = "yellow3";
static dbEntry e28_3 = {&e28_2, 205 * C, 205 * C, 0 * C, c28_3};
static const char c28_4[] = "yellow4";
static dbEntry e28_4 = {&e28_3, 139 * C, 139 * C, 0 * C, c28_4};
static const char c29_0[] = "lightsteelblue2";
static dbEntry e29_0 = {NULL, 188 * C, 210 * C, 238 * C, c29_0};
static const char c30_0[] = "lightsteelblue3";
static dbEntry e30_0 = {NULL, 162 * C, 181 * C, 205 * C, c30_0};
static const char c31_0[] = "lightsteelblue4";
static dbEntry e31_0 = {NULL, 110 * C, 123 * C, 139 * C, c31_0};
static const char c32_0[] = "gray0";
static dbEntry e32_0 = {NULL, 0 * C, 0 * C, 0 * C, c32_0};
static const char c33_0[] = "gray1";
static dbEntry e33_0 = {NULL, 3 * C, 3 * C, 3 * C, c33_0};
static const char c34_0[] = "grey0";
static dbEntry e34_0 = {NULL, 0 * C, 0 * C, 0 * C, c34_0};
static const char c34_1[] = "gray2";
static dbEntry e34_1 = {&e34_0, 5 * C, 5 * C, 5 * C, c34_1};
static const char c34_2[] = "gray100";
static dbEntry e34_2 = {&e34_1, 255 * C, 255 * C, 255 * C, c34_2};
static const char c35_0[] = "grey1";
static dbEntry e35_0 = {NULL, 3 * C, 3 * C, 3 * C, c35_0};
static const char c35_1[] = "gray3";
static dbEntry e35_1 = {&e35_0, 8 * C, 8 * C, 8 * C, c35_1};
static const char c35_2[] = "grey100";
static dbEntry e35_2 = {&e35_1, 255 * C, 255 * C, 255 * C, c35_2};
static const char c36_0[] = "grey2";
static dbEntry e36_0 = {NULL, 5 * C, 5 * C, 5 * C, c36_0};
static const char c36_1[] = "gray4";
static dbEntry e36_1 = {&e36_0, 10 * C, 10 * C, 10 * C, c36_1};
static const char c37_0[] = "grey3";
static dbEntry e37_0 = {NULL, 8 * C, 8 * C, 8 * C, c37_0};
static const char c37_1[] = "gray5";
static dbEntry e37_1 = {&e37_0, 13 * C, 13 * C, 13 * C, c37_1};
static const char c38_0[] = "thistle";
static dbEntry e38_0 = {NULL, 216 * C, 191 * C, 216 * C, c38_0};
static const char c38_1[] = "grey4";
static dbEntry e38_1 = {&e38_0, 10 * C, 10 * C, 10 * C, c38_1};
static const char c38_2[] = "gray6";
static dbEntry e38_2 = {&e38_1, 15 * C, 15 * C, 15 * C, c38_2};
static const char c39_0[] = "lightpink";
static dbEntry e39_0 = {NULL, 255 * C, 182 * C, 193 * C, c39_0};
static const char c39_1[] = "grey5";
static dbEntry e39_1 = {&e39_0, 13 * C, 13 * C, 13 * C, c39_1};
static const char c39_2[] = "gray7";
static dbEntry e39_2 = {&e39_1, 18 * C, 18 * C, 18 * C, c39_2};
static const char c40_0[] = "paleturquoise1";
static dbEntry e40_0 = {NULL, 187 * C, 255 * C, 255 * C, c40_0};
static const char c40_1[] = "grey6";
static dbEntry e40_1 = {&e40_0, 15 * C, 15 * C, 15 * C, c40_1};
static const char c40_2[] = "gray8";
static dbEntry e40_2 = {&e40_1, 20 * C, 20 * C, 20 * C, c40_2};
static const char c41_0[] = "paleturquoise2";
static dbEntry e41_0 = {NULL, 174 * C, 238 * C, 238 * C, c41_0};
static const char c41_1[] = "grey7";
static dbEntry e41_1 = {&e41_0, 18 * C, 18 * C, 18 * C, c41_1};
static const char c41_2[] = "gray9";
static dbEntry e41_2 = {&e41_1, 23 * C, 23 * C, 23 * C, c41_2};
static const char c42_0[] = "mintcream";
static dbEntry e42_0 = {NULL, 245 * C, 255 * C, 250 * C, c42_0};
static const char c42_1[] = "paleturquoise3";
static dbEntry e42_1 = {&e42_0, 150 * C, 205 * C, 205 * C, c42_1};
static const char c42_2[] = "green1";
static dbEntry e42_2 = {&e42_1, 0 * C, 255 * C, 0 * C, c42_2};
static const char c42_3[] = "magenta1";
static dbEntry e42_3 = {&e42_2, 255 * C, 0 * C, 255 * C, c42_3};
static const char c42_4[] = "magenta2";
static dbEntry e42_4 = {&e42_3, 238 * C, 0 * C, 238 * C, c42_4};
static const char c42_5[] = "magenta3";
static dbEntry e42_5 = {&e42_4, 205 * C, 0 * C, 205 * C, c42_5};
static const char c42_6[] = "magenta4";
static dbEntry e42_6 = {&e42_5, 139 * C, 0 * C, 139 * C, c42_6};
static const char c42_7[] = "grey8";
static dbEntry e42_7 = {&e42_6, 20 * C, 20 * C, 20 * C, c42_7};
static const char c43_0[] = "paleturquoise4";
static dbEntry e43_0 = {NULL, 102 * C, 139 * C, 139 * C, c43_0};
static const char c43_1[] = "green2";
static dbEntry e43_1 = {&e43_0, 0 * C, 238 * C, 0 * C, c43_1};
static const char c43_2[] = "grey9";
static dbEntry e43_2 = {&e43_1, 23 * C, 23 * C, 23 * C, c43_2};
static const char c44_0[] = "darkkhaki";
static dbEntry e44_0 = {NULL, 189 * C, 183 * C, 107 * C, c44_0};
static const char c44_1[] = "green3";
static dbEntry e44_1 = {&e44_0, 0 * C, 205 * C, 0 * C, c44_1};
static const char c45_0[] = "green4";
static dbEntry e45_0 = {NULL, 0 * C, 139 * C, 0 * C, c45_0};
static const char c47_0[] = "honeydew";
static dbEntry e47_0 = {NULL, 240 * C, 255 * C, 240 * C, c47_0};
static const char c47_1[] = "greenyellow";
static dbEntry e47_1 = {&e47_0, 173 * C, 255 * C, 47 * C, c47_1};
static const char c51_0[] = "yellowgreen";
static dbEntry e51_0 = {NULL, 154 * C, 205 * C, 50 * C, c51_0};
static const char c52_0[] = "darkslategrey";
static dbEntry e52_0 = {NULL, 47 * C, 79 * C, 79 * C, c52_0};
static const char c54_0[] = "mediumspringgreen";
static dbEntry e54_0 = {NULL, 0 * C, 250 * C, 154 * C, c54_0};
static const char c55_0[] = "deepskyblue";
static dbEntry e55_0 = {NULL, 0 * C, 191 * C, 255 * C, c55_0};
static const char c56_0[] = "lemonchiffon4";
static dbEntry e56_0 = {NULL, 139 * C, 137 * C, 112 * C, c56_0};
static const char c57_0[] = "lemonchiffon1";
static dbEntry e57_0 = {NULL, 255 * C, 250 * C, 205 * C, c57_0};
static const char c57_1[] = "blue1";
static dbEntry e57_1 = {&e57_0, 0 * C, 0 * C, 255 * C, c57_1};
static const char c58_0[] = "lemonchiffon2";
static dbEntry e58_0 = {NULL, 238 * C, 233 * C, 191 * C, c58_0};
static const char c58_1[] = "ivory1";
static dbEntry e58_1 = {&e58_0, 255 * C, 255 * C, 240 * C, c58_1};
static const char c58_2[] = "blue2";
static dbEntry e58_2 = {&e58_1, 0 * C, 0 * C, 238 * C, c58_2};
static const char c59_0[] = "olivedrab";
static dbEntry e59_0 = {NULL, 107 * C, 142 * C, 35 * C, c59_0};
static const char c59_1[] = "lemonchiffon3";
static dbEntry e59_1 = {&e59_0, 205 * C, 201 * C, 165 * C, c59_1};
static const char c59_2[] = "ivory2";
static dbEntry e59_2 = {&e59_1, 238 * C, 238 * C, 224 * C, c59_2};
static const char c59_3[] = "blue3";
static dbEntry e59_3 = {&e59_2, 0 * C, 0 * C, 205 * C, c59_3};
static const char c60_0[] = "ivory3";
static dbEntry e60_0 = {NULL, 205 * C, 205 * C, 193 * C, c60_0};
static const char c60_1[] = "blue4";
static dbEntry e60_1 = {&e60_0, 0 * C, 0 * C, 139 * C, c60_1};
static const char c61_0[] = "ivory4";
static dbEntry e61_0 = {NULL, 139 * C, 139 * C, 131 * C, c61_0};
static const char c62_0[] = "navyblue";
static dbEntry e62_0 = {NULL, 0 * C, 0 * C, 128 * C, c62_0};
static const char c62_1[] = "lightgoldenrodyellow";
static dbEntry e62_1 = {&e62_0, 250 * C, 250 * C, 210 * C, c62_1};
static const char c63_0[] = "grey";
static dbEntry e63_0 = {NULL, 190 * C, 190 * C, 190 * C, c63_0};
static const char c64_0[] = "springgreen1";
static dbEntry e64_0 = {NULL, 0 * C, 255 * C, 127 * C, c64_0};
static const char c65_0[] = "springgreen2";
static dbEntry e65_0 = {NULL, 0 * C, 238 * C, 118 * C, c65_0};
static const char c65_1[] = "gray10";
static dbEntry e65_1 = {&e65_0, 26 * C, 26 * C, 26 * C, c65_1};
static const char c66_0[] = "deepskyblue1";
static dbEntry e66_0 = {NULL, 0 * C, 191 * C, 255 * C, c66_0};
static const char c66_1[] = "springgreen3";
static dbEntry e66_1 = {&e66_0, 0 * C, 205 * C, 102 * C, c66_1};
static const char c66_2[] = "gray11";
static dbEntry e66_2 = {&e66_1, 28 * C, 28 * C, 28 * C, c66_2};
static const char c67_0[] = "deepskyblue2";
static dbEntry e67_0 = {NULL, 0 * C, 178 * C, 238 * C, c67_0};
static const char c67_1[] = "springgreen4";
static dbEntry e67_1 = {&e67_0, 0 * C, 139 * C, 69 * C, c67_1};
static const char c67_2[] = "gray12";
static dbEntry e67_2 = {&e67_1, 31 * C, 31 * C, 31 * C, c67_2};
static const char c68_0[] = "deepskyblue3";
static dbEntry e68_0 = {NULL, 0 * C, 154 * C, 205 * C, c68_0};
static const char c68_1[] = "gray13";
static dbEntry e68_1 = {&e68_0, 33 * C, 33 * C, 33 * C, c68_1};
static const char c69_0[] = "deepskyblue4";
static dbEntry e69_0 = {NULL, 0 * C, 104 * C, 139 * C, c69_0};
static const char c69_1[] = "gray14";
static dbEntry e69_1 = {&e69_0, 36 * C, 36 * C, 36 * C, c69_1};
static const char c70_0[] = "gray15";
static dbEntry e70_0 = {NULL, 38 * C, 38 * C, 38 * C, c70_0};
static const char c70_1[] = "lightgreen";
static dbEntry e70_1 = {&e70_0, 144 * C, 238 * C, 144 * C, c70_1};
static const char c71_0[] = "gray16";
static dbEntry e71_0 = {NULL, 41 * C, 41 * C, 41 * C, c71_0};
static const char c72_0[] = "gray17";
static dbEntry e72_0 = {NULL, 43 * C, 43 * C, 43 * C, c72_0};
static const char c73_0[] = "black";
static dbEntry e73_0 = {NULL, 0 * C, 0 * C, 0 * C, c73_0};
static const char c73_1[] = "gray18";
static dbEntry e73_1 = {&e73_0, 46 * C, 46 * C, 46 * C, c73_1};
static const char c74_0[] = "gray19";
static dbEntry e74_0 = {NULL, 48 * C, 48 * C, 48 * C, c74_0};
static const char c77_0[] = "peru";
static dbEntry e77_0 = {NULL, 205 * C, 133 * C, 63 * C, c77_0};
static const char c79_0[] = "beige";
static dbEntry e79_0 = {NULL, 245 * C, 245 * C, 220 * C, c79_0};
static const char c81_0[] = "gray20";
static dbEntry e81_0 = {NULL, 51 * C, 51 * C, 51 * C, c81_0};
static const char c82_0[] = "gray21";
static dbEntry e82_0 = {NULL, 54 * C, 54 * C, 54 * C, c82_0};
static const char c83_0[] = "gray22";
static dbEntry e83_0 = {NULL, 56 * C, 56 * C, 56 * C, c83_0};
static const char c84_0[] = "gray23";
static dbEntry e84_0 = {NULL, 59 * C, 59 * C, 59 * C, c84_0};
static const char c85_0[] = "gray24";
static dbEntry e85_0 = {NULL, 61 * C, 61 * C, 61 * C, c85_0};
static const char c86_0[] = "gray25";
static dbEntry e86_0 = {NULL, 64 * C, 64 * C, 64 * C, c86_0};
static const char c87_0[] = "gray26";
static dbEntry e87_0 = {NULL, 66 * C, 66 * C, 66 * C, c87_0};
static const char c88_0[] = "gray27";
static dbEntry e88_0 = {NULL, 69 * C, 69 * C, 69 * C, c88_0};
static const char c89_0[] = "gray28";
static dbEntry e89_0 = {NULL, 71 * C, 71 * C, 71 * C, c89_0};
static const char c90_0[] = "gray29";
static dbEntry e90_0 = {NULL, 74 * C, 74 * C, 74 * C, c90_0};
static const char c91_0[] = "lightskyblue";
static dbEntry e91_0 = {NULL, 135 * C, 206 * C, 250 * C, c91_0};
static const char c91_1[] = "seagreen";
static dbEntry e91_1 = {&e91_0, 46 * C, 139 * C, 87 * C, c91_1};
static const char c93_0[] = "linen";
static dbEntry e93_0 = {NULL, 250 * C, 240 * C, 230 * C, c93_0};
static const char c95_0[] = "salmon";
static dbEntry e95_0 = {NULL, 250 * C, 128 * C, 114 * C, c95_0};
static const char c97_0[] = "grey10";
static dbEntry e97_0 = {NULL, 26 * C, 26 * C, 26 * C, c97_0};
static const char c97_1[] = "gray30";
static dbEntry e97_1 = {&e97_0, 77 * C, 77 * C, 77 * C, c97_1};
static const char c98_0[] = "grey11";
static dbEntry e98_0 = {NULL, 28 * C, 28 * C, 28 * C, c98_0};
static const char c98_1[] = "gray31";
static dbEntry e98_1 = {&e98_0, 79 * C, 79 * C, 79 * C, c98_1};
static const char c99_0[] = "grey12";
static dbEntry e99_0 = {NULL, 31 * C, 31 * C, 31 * C, c99_0};
static const char c99_1[] = "gray32";
static dbEntry e99_1 = {&e99_0, 82 * C, 82 * C, 82 * C, c99_1};
static const char c100_0[] = "grey13";
static dbEntry e100_0 = {NULL, 33 * C, 33 * C, 33 * C, c100_0};
static const char c100_1[] = "gray33";
static dbEntry e100_1 = {&e100_0, 84 * C, 84 * C, 84 * C, c100_1};
static const char c100_2[] = "darkcyan";
static dbEntry e100_2 = {&e100_1, 0 * C, 139 * C, 139 * C, c100_2};
static const char c101_0[] = "grey14";
static dbEntry e101_0 = {NULL, 36 * C, 36 * C, 36 * C, c101_0};
static const char c101_1[] = "gray34";
static dbEntry e101_1 = {&e101_0, 87 * C, 87 * C, 87 * C, c101_1};
static const char c102_0[] = "grey15";
static dbEntry e102_0 = {NULL, 38 * C, 38 * C, 38 * C, c102_0};
static const char c102_1[] = "gray35";
static dbEntry e102_1 = {&e102_0, 89 * C, 89 * C, 89 * C, c102_1};
static const char c103_0[] = "grey16";
static dbEntry e103_0 = {NULL, 41 * C, 41 * C, 41 * C, c103_0};
static const char c103_1[] = "gray36";
static dbEntry e103_1 = {&e103_0, 92 * C, 92 * C, 92 * C, c103_1};
static const char c104_0[] = "grey17";
static dbEntry e104_0 = {NULL, 43 * C, 43 * C, 43 * C, c104_0};
static const char c104_1[] = "gray37";
static dbEntry e104_1 = {&e104_0, 94 * C, 94 * C, 94 * C, c104_1};
static const char c105_0[] = "grey18";
static dbEntry e105_0 = {NULL, 46 * C, 46 * C, 46 * C, c105_0};
static const char c105_1[] = "gray38";
static dbEntry e105_1 = {&e105_0, 97 * C, 97 * C, 97 * C, c105_1};
static const char c106_0[] = "steelblue4";
static dbEntry e106_0 = {NULL, 54 * C, 100 * C, 139 * C, c106_0};
static const char c106_1[] = "grey19";
static dbEntry e106_1 = {&e106_0, 48 * C, 48 * C, 48 * C, c106_1};
static const char c106_2[] = "gray39";
static dbEntry e106_2 = {&e106_1, 99 * C, 99 * C, 99 * C, c106_2};
static const char c107_0[] = "mediumblue";
static dbEntry e107_0 = {NULL, 0 * C, 0 * C, 205 * C, c107_0};
static const char c107_1[] = "steelblue1";
static dbEntry e107_1 = {&e107_0, 99 * C, 184 * C, 255 * C, c107_1};
static const char c108_0[] = "steelblue2";
static dbEntry e108_0 = {NULL, 92 * C, 172 * C, 238 * C, c108_0};
static const char c108_1[] = "firebrick1";
static dbEntry e108_1 = {&e108_0, 255 * C, 48 * C, 48 * C, c108_1};
static const char c108_2[] = "firebrick2";
static dbEntry e108_2 = {&e108_1, 238 * C, 44 * C, 44 * C, c108_2};
static const char c108_3[] = "firebrick3";
static dbEntry e108_3 = {&e108_2, 205 * C, 38 * C, 38 * C, c108_3};
static const char c109_0[] = "steelblue3";
static dbEntry e109_0 = {NULL, 79 * C, 148 * C, 205 * C, c109_0};
static const char c110_0[] = "lightcyan1";
static dbEntry e110_0 = {NULL, 224 * C, 255 * C, 255 * C, c110_0};
static const char c110_1[] = "lightcyan2";
static dbEntry e110_1 = {&e110_0, 209 * C, 238 * C, 238 * C, c110_1};
static const char c110_2[] = "lightcyan3";
static dbEntry e110_2 = {&e110_1, 180 * C, 205 * C, 205 * C, c110_2};
static const char c110_3[] = "lightcyan4";
static dbEntry e110_3 = {&e110_2, 122 * C, 139 * C, 139 * C, c110_3};
static const char c111_0[] = "brown1";
static dbEntry e111_0 = {NULL, 255 * C, 64 * C, 64 * C, c111_0};
static const char c112_0[] = "firebrick4";
static dbEntry e112_0 = {NULL, 139 * C, 26 * C, 26 * C, c112_0};
static const char c112_1[] = "brown2";
static dbEntry e112_1 = {&e112_0, 238 * C, 59 * C, 59 * C, c112_1};
static const char c112_2[] = "lightpink1";
static dbEntry e112_2 = {&e112_1, 255 * C, 174 * C, 185 * C, c112_2};
static const char c112_3[] = "lightpink2";
static dbEntry e112_3 = {&e112_2, 238 * C, 162 * C, 173 * C, c112_3};
static const char c112_4[] = "lightpink3";
static dbEntry e112_4 = {&e112_3, 205 * C, 140 * C, 149 * C, c112_4};
static const char c112_5[] = "lightpink4";
static dbEntry e112_5 = {&e112_4, 139 * C, 95 * C, 101 * C, c112_5};
static const char c113_0[] = "brown3";
static dbEntry e113_0 = {NULL, 205 * C, 51 * C, 51 * C, c113_0};
static const char c113_1[] = "grey20";
static dbEntry e113_1 = {&e113_0, 51 * C, 51 * C, 51 * C, c113_1};
static const char c113_2[] = "gray40";
static dbEntry e113_2 = {&e113_1, 102 * C, 102 * C, 102 * C, c113_2};
static const char c114_0[] = "brown4";
static dbEntry e114_0 = {NULL, 139 * C, 35 * C, 35 * C, c114_0};
static const char c114_1[] = "grey21";
static dbEntry e114_1 = {&e114_0, 54 * C, 54 * C, 54 * C, c114_1};
static const char c114_2[] = "gray41";
static dbEntry e114_2 = {&e114_1, 105 * C, 105 * C, 105 * C, c114_2};
static const char c115_0[] = "slategray";
static dbEntry e115_0 = {NULL, 112 * C, 128 * C, 144 * C, c115_0};
static const char c115_1[] = "lightskyblue1";
static dbEntry e115_1 = {&e115_0, 176 * C, 226 * C, 255 * C, c115_1};
static const char c115_2[] = "grey22";
static dbEntry e115_2 = {&e115_1, 56 * C, 56 * C, 56 * C, c115_2};
static const char c115_3[] = "gray42";
static dbEntry e115_3 = {&e115_2, 107 * C, 107 * C, 107 * C, c115_3};
static const char c116_0[] = "lightskyblue2";
static dbEntry e116_0 = {NULL, 164 * C, 211 * C, 238 * C, c116_0};
static const char c116_1[] = "grey23";
static dbEntry e116_1 = {&e116_0, 59 * C, 59 * C, 59 * C, c116_1};
static const char c116_2[] = "gray43";
static dbEntry e116_2 = {&e116_1, 110 * C, 110 * C, 110 * C, c116_2};
static const char c117_0[] = "lightskyblue3";
static dbEntry e117_0 = {NULL, 141 * C, 182 * C, 205 * C, c117_0};
static const char c117_1[] = "grey24";
static dbEntry e117_1 = {&e117_0, 61 * C, 61 * C, 61 * C, c117_1};
static const char c117_2[] = "gray44";
static dbEntry e117_2 = {&e117_1, 112 * C, 112 * C, 112 * C, c117_2};
static const char c118_0[] = "lightskyblue4";
static dbEntry e118_0 = {NULL, 96 * C, 123 * C, 139 * C, c118_0};
static const char c118_1[] = "grey25";
static dbEntry e118_1 = {&e118_0, 64 * C, 64 * C, 64 * C, c118_1};
static const char c118_2[] = "gray45";
static dbEntry e118_2 = {&e118_1, 115 * C, 115 * C, 115 * C, c118_2};
static const char c119_0[] = "grey26";
static dbEntry e119_0 = {NULL, 66 * C, 66 * C, 66 * C, c119_0};
static const char c119_1[] = "gray46";
static dbEntry e119_1 = {&e119_0, 117 * C, 117 * C, 117 * C, c119_1};
static const char c120_0[] = "maroon";
static dbEntry e120_0 = {NULL, 176 * C, 48 * C, 96 * C, c120_0};
static const char c120_1[] = "grey27";
static dbEntry e120_1 = {&e120_0, 69 * C, 69 * C, 69 * C, c120_1};
static const char c120_2[] = "gray47";
static dbEntry e120_2 = {&e120_1, 120 * C, 120 * C, 120 * C, c120_2};
static const char c121_0[] = "grey28";
static dbEntry e121_0 = {NULL, 71 * C, 71 * C, 71 * C, c121_0};
static const char c121_1[] = "gray48";
static dbEntry e121_1 = {&e121_0, 122 * C, 122 * C, 122 * C, c121_1};
static const char c122_0[] = "grey29";
static dbEntry e122_0 = {NULL, 74 * C, 74 * C, 74 * C, c122_0};
static const char c122_1[] = "gray49";
static dbEntry e122_1 = {&e122_0, 125 * C, 125 * C, 125 * C, c122_1};
static const char c124_0[] = "lightsalmon1";
static dbEntry e124_0 = {NULL, 255 * C, 160 * C, 122 * C, c124_0};
static const char c125_0[] = "lightsalmon2";
static dbEntry e125_0 = {NULL, 238 * C, 149 * C, 114 * C, c125_0};
static const char c125_1[] = "deeppink4";
static dbEntry e125_1 = {&e125_0, 139 * C, 10 * C, 80 * C, c125_1};
static const char c126_0[] = "lightsalmon3";
static dbEntry e126_0 = {NULL, 205 * C, 129 * C, 98 * C, c126_0};
static const char c126_1[] = "deeppink1";
static dbEntry e126_1 = {&e126_0, 255 * C, 20 * C, 147 * C, c126_1};
static const char c127_0[] = "peachpuff";
static dbEntry e127_0 = {NULL, 255 * C, 218 * C, 185 * C, c127_0};
static const char c127_1[] = "navy";
static dbEntry e127_1 = {&e127_0, 0 * C, 0 * C, 128 * C, c127_1};
static const char c127_2[] = "lightsalmon4";
static dbEntry e127_2 = {&e127_1, 139 * C, 87 * C, 66 * C, c127_2};
static const char c127_3[] = "deeppink2";
static dbEntry e127_3 = {&e127_2, 238 * C, 18 * C, 137 * C, c127_3};
static const char c128_0[] = "violetred";
static dbEntry e128_0 = {NULL, 208 * C, 32 * C, 144 * C, c128_0};
static const char c128_1[] = "deeppink3";
static dbEntry e128_1 = {&e128_0, 205 * C, 16 * C, 118 * C, c128_1};
static const char c129_0[] = "pink1";
static dbEntry e129_0 = {NULL, 255 * C, 181 * C, 197 * C, c129_0};
static const char c129_1[] = "grey30";
static dbEntry e129_1 = {&e129_0, 77 * C, 77 * C, 77 * C, c129_1};
static const char c129_2[] = "gray50";
static dbEntry e129_2 = {&e129_1, 127 * C, 127 * C, 127 * C, c129_2};
static const char c130_0[] = "pink2";
static dbEntry e130_0 = {NULL, 238 * C, 169 * C, 184 * C, c130_0};
static const char c130_1[] = "grey31";
static dbEntry e130_1 = {&e130_0, 79 * C, 79 * C, 79 * C, c130_1};
static const char c130_2[] = "gray51";
static dbEntry e130_2 = {&e130_1, 130 * C, 130 * C, 130 * C, c130_2};
static const char c131_0[] = "pink3";
static dbEntry e131_0 = {NULL, 205 * C, 145 * C, 158 * C, c131_0};
static const char c131_1[] = "grey32";
static dbEntry e131_1 = {&e131_0, 82 * C, 82 * C, 82 * C, c131_1};
static const char c131_2[] = "gray52";
static dbEntry e131_2 = {&e131_1, 133 * C, 133 * C, 133 * C, c131_2};
static const char c132_0[] = "darksalmon";
static dbEntry e132_0 = {NULL, 233 * C, 150 * C, 122 * C, c132_0};
static const char c132_1[] = "pink4";
static dbEntry e132_1 = {&e132_0, 139 * C, 99 * C, 108 * C, c132_1};
static const char c132_2[] = "grey33";
static dbEntry e132_2 = {&e132_1, 84 * C, 84 * C, 84 * C, c132_2};
static const char c132_3[] = "gray53";
static dbEntry e132_3 = {&e132_2, 135 * C, 135 * C, 135 * C, c132_3};
static const char c133_0[] = "grey34";
static dbEntry e133_0 = {NULL, 87 * C, 87 * C, 87 * C, c133_0};
static const char c133_1[] = "gray54";
static dbEntry e133_1 = {&e133_0, 138 * C, 138 * C, 138 * C, c133_1};
static const char c134_0[] = "grey35";
static dbEntry e134_0 = {NULL, 89 * C, 89 * C, 89 * C, c134_0};
static const char c134_1[] = "gray55";
static dbEntry e134_1 = {&e134_0, 140 * C, 140 * C, 140 * C, c134_1};
static const char c135_0[] = "lightseagreen";
static dbEntry e135_0 = {NULL, 32 * C, 178 * C, 170 * C, c135_0};
static const char c135_1[] = "grey36";
static dbEntry e135_1 = {&e135_0, 92 * C, 92 * C, 92 * C, c135_1};
static const char c135_2[] = "gray56";
static dbEntry e135_2 = {&e135_1, 143 * C, 143 * C, 143 * C, c135_2};
static const char c136_0[] = "grey37";
static dbEntry e136_0 = {NULL, 94 * C, 94 * C, 94 * C, c136_0};
static const char c136_1[] = "gray57";
static dbEntry e136_1 = {&e136_0, 145 * C, 145 * C, 145 * C, c136_1};
static const char c137_0[] = "grey38";
static dbEntry e137_0 = {NULL, 97 * C, 97 * C, 97 * C, c137_0};
static const char c137_1[] = "gray58";
static dbEntry e137_1 = {&e137_0, 148 * C, 148 * C, 148 * C, c137_1};
static const char c138_0[] = "goldenrod2";
static dbEntry e138_0 = {NULL, 238 * C, 180 * C, 34 * C, c138_0};
static const char c138_1[] = "grey39";
static dbEntry e138_1 = {&e138_0, 99 * C, 99 * C, 99 * C, c138_1};
static const char c138_2[] = "gray59";
static dbEntry e138_2 = {&e138_1, 150 * C, 150 * C, 150 * C, c138_2};
static const char c139_0[] = "chocolate";
static dbEntry e139_0 = {NULL, 210 * C, 105 * C, 30 * C, c139_0};
static const char c139_1[] = "goldenrod1";
static dbEntry e139_1 = {&e139_0, 255 * C, 193 * C, 37 * C, c139_1};
static const char c139_2[] = "goldenrod3";
static dbEntry e139_2 = {&e139_1, 205 * C, 155 * C, 29 * C, c139_2};
static const char c140_0[] = "lightyellow1";
static dbEntry e140_0 = {NULL, 255 * C, 255 * C, 224 * C, c140_0};
static const char c141_0[] = "lightyellow2";
static dbEntry e141_0 = {NULL, 238 * C, 238 * C, 209 * C, c141_0};
static const char c142_0[] = "lightyellow3";
static dbEntry e142_0 = {NULL, 205 * C, 205 * C, 180 * C, c142_0};
static const char c142_1[] = "goldenrod4";
static dbEntry e142_1 = {&e142_0, 139 * C, 105 * C, 20 * C, c142_1};
static const char c143_0[] = "lightyellow4";
static dbEntry e143_0 = {NULL, 139 * C, 139 * C, 122 * C, c143_0};
static const char c145_0[] = "lightslategray";
static dbEntry e145_0 = {NULL, 119 * C, 136 * C, 153 * C, c145_0};
static const char c145_1[] = "grey40";
static dbEntry e145_1 = {&e145_0, 102 * C, 102 * C, 102 * C, c145_1};
static const char c145_2[] = "gray60";
static dbEntry e145_2 = {&e145_1, 153 * C, 153 * C, 153 * C, c145_2};
static const char c146_0[] = "turquoise";
static dbEntry e146_0 = {NULL, 64 * C, 224 * C, 208 * C, c146_0};
static const char c146_1[] = "seagreen1";
static dbEntry e146_1 = {&e146_0, 84 * C, 255 * C, 159 * C, c146_1};
static const char c146_2[] = "seagreen2";
static dbEntry e146_2 = {&e146_1, 78 * C, 238 * C, 148 * C, c146_2};
static const char c146_3[] = "seagreen3";
static dbEntry e146_3 = {&e146_2, 67 * C, 205 * C, 128 * C, c146_3};
static const char c146_4[] = "seagreen4";
static dbEntry e146_4 = {&e146_3, 46 * C, 139 * C, 87 * C, c146_4};
static const char c146_5[] = "grey41";
static dbEntry e146_5 = {&e146_4, 105 * C, 105 * C, 105 * C, c146_5};
static const char c146_6[] = "gray61";
static dbEntry e146_6 = {&e146_5, 156 * C, 156 * C, 156 * C, c146_6};
static const char c147_0[] = "darkseagreen";
static dbEntry e147_0 = {NULL, 143 * C, 188 * C, 143 * C, c147_0};
static const char c147_1[] = "peachpuff1";
static dbEntry e147_1 = {&e147_0, 255 * C, 218 * C, 185 * C, c147_1};
static const char c147_2[] = "grey42";
static dbEntry e147_2 = {&e147_1, 107 * C, 107 * C, 107 * C, c147_2};
static const char c147_3[] = "gray62";
static dbEntry e147_3 = {&e147_2, 158 * C, 158 * C, 158 * C, c147_3};
static const char c148_0[] = "grey43";
static dbEntry e148_0 = {NULL, 110 * C, 110 * C, 110 * C, c148_0};
static const char c148_1[] = "gray63";
static dbEntry e148_1 = {&e148_0, 161 * C, 161 * C, 161 * C, c148_1};
static const char c149_0[] = "peachpuff2";
static dbEntry e149_0 = {NULL, 238 * C, 203 * C, 173 * C, c149_0};
static const char c149_1[] = "peachpuff3";
static dbEntry e149_1 = {&e149_0, 205 * C, 175 * C, 149 * C, c149_1};
static const char c149_2[] = "grey44";
static dbEntry e149_2 = {&e149_1, 112 * C, 112 * C, 112 * C, c149_2};
static const char c149_3[] = "gray64";
static dbEntry e149_3 = {&e149_2, 163 * C, 163 * C, 163 * C, c149_3};
static const char c150_0[] = "grey45";
static dbEntry e150_0 = {NULL, 115 * C, 115 * C, 115 * C, c150_0};
static const char c150_1[] = "gray65";
static dbEntry e150_1 = {&e150_0, 166 * C, 166 * C, 166 * C, c150_1};
static const char c151_0[] = "peachpuff4";
static dbEntry e151_0 = {NULL, 139 * C, 119 * C, 101 * C, c151_0};
static const char c151_1[] = "grey46";
static dbEntry e151_1 = {&e151_0, 117 * C, 117 * C, 117 * C, c151_1};
static const char c151_2[] = "gray66";
static dbEntry e151_2 = {&e151_1, 168 * C, 168 * C, 168 * C, c151_2};
static const char c152_0[] = "grey47";
static dbEntry e152_0 = {NULL, 120 * C, 120 * C, 120 * C, c152_0};
static const char c152_1[] = "gray67";
static dbEntry e152_1 = {&e152_0, 171 * C, 171 * C, 171 * C, c152_1};
static const char c153_0[] = "wheat";
static dbEntry e153_0 = {NULL, 245 * C, 222 * C, 179 * C, c153_0};
static const char c153_1[] = "grey48";
static dbEntry e153_1 = {&e153_0, 122 * C, 122 * C, 122 * C, c153_1};
static const char c153_2[] = "gray68";
static dbEntry e153_2 = {&e153_1, 173 * C, 173 * C, 173 * C, c153_2};
static const char c154_0[] = "mediumaquamarine";
static dbEntry e154_0 = {NULL, 102 * C, 205 * C, 170 * C, c154_0};
static const char c154_1[] = "grey49";
static dbEntry e154_1 = {&e154_0, 125 * C, 125 * C, 125 * C, c154_1};
static const char c154_2[] = "gray69";
static dbEntry e154_2 = {&e154_1, 176 * C, 176 * C, 176 * C, c154_2};
static const char c161_0[] = "grey50";
static dbEntry e161_0 = {NULL, 127 * C, 127 * C, 127 * C, c161_0};
static const char c161_1[] = "gray70";
static dbEntry e161_1 = {&e161_0, 179 * C, 179 * C, 179 * C, c161_1};
static const char c162_0[] = "floralwhite";
static dbEntry e162_0 = {NULL, 255 * C, 250 * C, 240 * C, c162_0};
static const char c162_1[] = "grey51";
static dbEntry e162_1 = {&e162_0, 130 * C, 130 * C, 130 * C, c162_1};
static const char c162_2[] = "gray71";
static dbEntry e162_2 = {&e162_1, 181 * C, 181 * C, 181 * C, c162_2};
static const char c163_0[] = "chartreuse";
static dbEntry e163_0 = {NULL, 127 * C, 255 * C, 0 * C, c163_0};
static const char c163_1[] = "grey52";
static dbEntry e163_1 = {&e163_0, 133 * C, 133 * C, 133 * C, c163_1};
static const char c163_2[] = "gray72";
static dbEntry e163_2 = {&e163_1, 184 * C, 184 * C, 184 * C, c163_2};
static const char c164_0[] = "grey53";
static dbEntry e164_0 = {NULL, 135 * C, 135 * C, 135 * C, c164_0};
static const char c164_1[] = "gray73";
static dbEntry e164_1 = {&e164_0, 186 * C, 186 * C, 186 * C, c164_1};
static const char c165_0[] = "grey54";
static dbEntry e165_0 = {NULL, 138 * C, 138 * C, 138 * C, c165_0};
static const char c165_1[] = "gray74";
static dbEntry e165_1 = {&e165_0, 189 * C, 189 * C, 189 * C, c165_1};
static const char c166_0[] = "grey55";
static dbEntry e166_0 = {NULL, 140 * C, 140 * C, 140 * C, c166_0};
static const char c166_1[] = "gray75";
static dbEntry e166_1 = {&e166_0, 191 * C, 191 * C, 191 * C, c166_1};
static const char c167_0[] = "grey56";
static dbEntry e167_0 = {NULL, 143 * C, 143 * C, 143 * C, c167_0};
static const char c167_1[] = "gray76";
static dbEntry e167_1 = {&e167_0, 194 * C, 194 * C, 194 * C, c167_1};
static const char c168_0[] = "mediumslateblue";
static dbEntry e168_0 = {NULL, 123 * C, 104 * C, 238 * C, c168_0};
static const char c168_1[] = "palevioletred";
static dbEntry e168_1 = {&e168_0, 219 * C, 112 * C, 147 * C, c168_1};
static const char c168_2[] = "grey57";
static dbEntry e168_2 = {&e168_1, 145 * C, 145 * C, 145 * C, c168_2};
static const char c168_3[] = "gray77";
static dbEntry e168_3 = {&e168_2, 196 * C, 196 * C, 196 * C, c168_3};
static const char c169_0[] = "darkorchid2";
static dbEntry e169_0 = {NULL, 178 * C, 58 * C, 238 * C, c169_0};
static const char c169_1[] = "darkorchid4";
static dbEntry e169_1 = {&e169_0, 104 * C, 34 * C, 139 * C, c169_1};
static const char c169_2[] = "grey58";
static dbEntry e169_2 = {&e169_1, 148 * C, 148 * C, 148 * C, c169_2};
static const char c169_3[] = "gray78";
static dbEntry e169_3 = {&e169_2, 199 * C, 199 * C, 199 * C, c169_3};
static const char c170_0[] = "darkorchid1";
static dbEntry e170_0 = {NULL, 191 * C, 62 * C, 255 * C, c170_0};
static const char c170_1[] = "darkorchid3";
static dbEntry e170_1 = {&e170_0, 154 * C, 50 * C, 205 * C, c170_1};
static const char c170_2[] = "grey59";
static dbEntry e170_2 = {&e170_1, 150 * C, 150 * C, 150 * C, c170_2};
static const char c170_3[] = "gray79";
static dbEntry e170_3 = {&e170_2, 201 * C, 201 * C, 201 * C, c170_3};
static const char c172_0[] = "mistyrose4";
static dbEntry e172_0 = {NULL, 139 * C, 125 * C, 123 * C, c172_0};
static const char c173_0[] = "mistyrose1";
static dbEntry e173_0 = {NULL, 255 * C, 228 * C, 225 * C, c173_0};
static const char c173_1[] = "dodgerblue4";
static dbEntry e173_1 = {&e173_0, 16 * C, 78 * C, 139 * C, c173_1};
static const char c174_0[] = "oldlace";
static dbEntry e174_0 = {NULL, 253 * C, 245 * C, 230 * C, c174_0};
static const char c174_1[] = "bisque";
static dbEntry e174_1 = {&e174_0, 255 * C, 228 * C, 196 * C, c174_1};
static const char c174_2[] = "mistyrose2";
static dbEntry e174_2 = {&e174_1, 238 * C, 213 * C, 210 * C, c174_2};
static const char c174_3[] = "dodgerblue1";
static dbEntry e174_3 = {&e174_2, 30 * C, 144 * C, 255 * C, c174_3};
static const char c174_4[] = "lightblue1";
static dbEntry e174_4 = {&e174_3, 191 * C, 239 * C, 255 * C, c174_4};
static const char c174_5[] = "lightblue2";
static dbEntry e174_5 = {&e174_4, 178 * C, 223 * C, 238 * C, c174_5};
static const char c174_6[] = "lightblue3";
static dbEntry e174_6 = {&e174_5, 154 * C, 192 * C, 205 * C, c174_6};
static const char c174_7[] = "lightblue4";
static dbEntry e174_7 = {&e174_6, 104 * C, 131 * C, 139 * C, c174_7};
static const char c175_0[] = "antiquewhite";
static dbEntry e175_0 = {NULL, 250 * C, 235 * C, 215 * C, c175_0};
static const char c175_1[] = "mistyrose3";
static dbEntry e175_1 = {&e175_0, 205 * C, 183 * C, 181 * C, c175_1};
static const char c175_2[] = "dodgerblue2";
static dbEntry e175_2 = {&e175_1, 28 * C, 134 * C, 238 * C, c175_2};
static const char c176_0[] = "dodgerblue3";
static dbEntry e176_0 = {NULL, 24 * C, 116 * C, 205 * C, c176_0};
static const char c177_0[] = "grey60";
static dbEntry e177_0 = {NULL, 153 * C, 153 * C, 153 * C, c177_0};
static const char c177_1[] = "gray80";
static dbEntry e177_1 = {&e177_0, 204 * C, 204 * C, 204 * C, c177_1};
static const char c178_0[] = "grey61";
static dbEntry e178_0 = {NULL, 156 * C, 156 * C, 156 * C, c178_0};
static const char c178_1[] = "gray81";
static dbEntry e178_1 = {&e178_0, 207 * C, 207 * C, 207 * C, c178_1};
static const char c179_0[] = "slategrey";
static dbEntry e179_0 = {NULL, 112 * C, 128 * C, 144 * C, c179_0};
static const char c179_1[] = "grey62";
static dbEntry e179_1 = {&e179_0, 158 * C, 158 * C, 158 * C, c179_1};
static const char c179_2[] = "gray82";
static dbEntry e179_2 = {&e179_1, 209 * C, 209 * C, 209 * C, c179_2};
static const char c180_0[] = "mediumorchid";
static dbEntry e180_0 = {NULL, 186 * C, 85 * C, 211 * C, c180_0};
static const char c180_1[] = "grey63";
static dbEntry e180_1 = {&e180_0, 161 * C, 161 * C, 161 * C, c180_1};
static const char c180_2[] = "gray83";
static dbEntry e180_2 = {&e180_1, 212 * C, 212 * C, 212 * C, c180_2};
static const char c181_0[] = "grey64";
static dbEntry e181_0 = {NULL, 163 * C, 163 * C, 163 * C, c181_0};
static const char c181_1[] = "gray84";
static dbEntry e181_1 = {&e181_0, 214 * C, 214 * C, 214 * C, c181_1};
static const char c182_0[] = "grey65";
static dbEntry e182_0 = {NULL, 166 * C, 166 * C, 166 * C, c182_0};
static const char c182_1[] = "gray85";
static dbEntry e182_1 = {&e182_0, 217 * C, 217 * C, 217 * C, c182_1};
static const char c183_0[] = "grey66";
static dbEntry e183_0 = {NULL, 168 * C, 168 * C, 168 * C, c183_0};
static const char c183_1[] = "gray86";
static dbEntry e183_1 = {&e183_0, 219 * C, 219 * C, 219 * C, c183_1};
static const char c184_0[] = "sienna1";
static dbEntry e184_0 = {NULL, 255 * C, 130 * C, 71 * C, c184_0};
static const char c184_1[] = "orangered4";
static dbEntry e184_1 = {&e184_0, 139 * C, 37 * C, 0 * C, c184_1};
static const char c184_2[] = "grey67";
static dbEntry e184_2 = {&e184_1, 171 * C, 171 * C, 171 * C, c184_2};
static const char c184_3[] = "gray87";
static dbEntry e184_3 = {&e184_2, 222 * C, 222 * C, 222 * C, c184_3};
static const char c185_0[] = "orangered1";
static dbEntry e185_0 = {NULL, 255 * C, 69 * C, 0 * C, c185_0};
static const char c185_1[] = "grey68";
static dbEntry e185_1 = {&e185_0, 173 * C, 173 * C, 173 * C, c185_1};
static const char c185_2[] = "gray88";
static dbEntry e185_2 = {&e185_1, 224 * C, 224 * C, 224 * C, c185_2};
static const char c186_0[] = "sienna2";
static dbEntry e186_0 = {NULL, 238 * C, 121 * C, 66 * C, c186_0};
static const char c186_1[] = "sienna3";
static dbEntry e186_1 = {&e186_0, 205 * C, 104 * C, 57 * C, c186_1};
static const char c186_2[] = "orangered2";
static dbEntry e186_2 = {&e186_1, 238 * C, 64 * C, 0 * C, c186_2};
static const char c186_3[] = "grey69";
static dbEntry e186_3 = {&e186_2, 176 * C, 176 * C, 176 * C, c186_3};
static const char c186_4[] = "gray89";
static dbEntry e186_4 = {&e186_3, 227 * C, 227 * C, 227 * C, c186_4};
static const char c187_0[] = "tan";
static dbEntry e187_0 = {NULL, 210 * C, 180 * C, 140 * C, c187_0};
static const char c187_1[] = "orangered3";
static dbEntry e187_1 = {&e187_0, 205 * C, 55 * C, 0 * C, c187_1};
static const char c188_0[] = "sienna4";
static dbEntry e188_0 = {NULL, 139 * C, 71 * C, 38 * C, c188_0};
static const char c193_0[] = "grey70";
static dbEntry e193_0 = {NULL, 179 * C, 179 * C, 179 * C, c193_0};
static const char c193_1[] = "gray90";
static dbEntry e193_1 = {&e193_0, 229 * C, 229 * C, 229 * C, c193_1};
static const char c194_0[] = "grey71";
static dbEntry e194_0 = {NULL, 181 * C, 181 * C, 181 * C, c194_0};
static const char c194_1[] = "gray91";
static dbEntry e194_1 = {&e194_0, 232 * C, 232 * C, 232 * C, c194_1};
static const char c195_0[] = "grey72";
static dbEntry e195_0 = {NULL, 184 * C, 184 * C, 184 * C, c195_0};
static const char c195_1[] = "gray92";
static dbEntry e195_1 = {&e195_0, 235 * C, 235 * C, 235 * C, c195_1};
static const char c196_0[] = "saddlebrown";
static dbEntry e196_0 = {NULL, 139 * C, 69 * C, 19 * C, c196_0};
static const char c196_1[] = "grey73";
static dbEntry e196_1 = {&e196_0, 186 * C, 186 * C, 186 * C, c196_1};
static const char c196_2[] = "gray93";
static dbEntry e196_2 = {&e196_1, 237 * C, 237 * C, 237 * C, c196_2};
static const char c197_0[] = "grey74";
static dbEntry e197_0 = {NULL, 189 * C, 189 * C, 189 * C, c197_0};
static const char c197_1[] = "gray94";
static dbEntry e197_1 = {&e197_0, 240 * C, 240 * C, 240 * C, c197_1};
static const char c198_0[] = "lightcoral";
static dbEntry e198_0 = {NULL, 240 * C, 128 * C, 128 * C, c198_0};
static const char c198_1[] = "grey75";
static dbEntry e198_1 = {&e198_0, 191 * C, 191 * C, 191 * C, c198_1};
static const char c198_2[] = "gray95";
static dbEntry e198_2 = {&e198_1, 242 * C, 242 * C, 242 * C, c198_2};
static const char c199_0[] = "burlywood";
static dbEntry e199_0 = {NULL, 222 * C, 184 * C, 135 * C, c199_0};
static const char c199_1[] = "grey76";
static dbEntry e199_1 = {&e199_0, 194 * C, 194 * C, 194 * C, c199_1};
static const char c199_2[] = "gray96";
static dbEntry e199_2 = {&e199_1, 245 * C, 245 * C, 245 * C, c199_2};
static const char c200_0[] = "darkorange2";
static dbEntry e200_0 = {NULL, 238 * C, 118 * C, 0 * C, c200_0};
static const char c200_1[] = "darkorange4";
static dbEntry e200_1 = {&e200_0, 139 * C, 69 * C, 0 * C, c200_1};
static const char c200_2[] = "grey77";
static dbEntry e200_2 = {&e200_1, 196 * C, 196 * C, 196 * C, c200_2};
static const char c200_3[] = "gray97";
static dbEntry e200_3 = {&e200_2, 247 * C, 247 * C, 247 * C, c200_3};
static const char c201_0[] = "darkorange1";
static dbEntry e201_0 = {NULL, 255 * C, 127 * C, 0 * C, c201_0};
static const char c201_1[] = "darkorange3";
static dbEntry e201_1 = {&e201_0, 205 * C, 102 * C, 0 * C, c201_1};
static const char c201_2[] = "grey78";
static dbEntry e201_2 = {&e201_1, 199 * C, 199 * C, 199 * C, c201_2};
static const char c201_3[] = "gray98";
static dbEntry e201_3 = {&e201_2, 250 * C, 250 * C, 250 * C, c201_3};
static const char c202_0[] = "khaki1";
static dbEntry e202_0 = {NULL, 255 * C, 246 * C, 143 * C, c202_0};
static const char c202_1[] = "grey79";
static dbEntry e202_1 = {&e202_0, 201 * C, 201 * C, 201 * C, c202_1};
static const char c202_2[] = "gray99";
static dbEntry e202_2 = {&e202_1, 252 * C, 252 * C, 252 * C, c202_2};
static const char c203_0[] = "khaki2";
static dbEntry e203_0 = {NULL, 238 * C, 230 * C, 133 * C, c203_0};
static const char c204_0[] = "khaki3";
static dbEntry e204_0 = {NULL, 205 * C, 198 * C, 115 * C, c204_0};
static const char c205_0[] = "khaki4";
static dbEntry e205_0 = {NULL, 139 * C, 134 * C, 78 * C, c205_0};
static const char c207_0[] = "darkgreen";
static dbEntry e207_0 = {NULL, 0 * C, 100 * C, 0 * C, c207_0};
static const char c207_1[] = "darkolivegreen";
static dbEntry e207_1 = {&e207_0, 85 * C, 107 * C, 47 * C, c207_1};
static const char c209_0[] = "lightslategrey";
static dbEntry e209_0 = {NULL, 119 * C, 136 * C, 153 * C, c209_0};
static const char c209_1[] = "grey80";
static dbEntry e209_1 = {&e209_0, 204 * C, 204 * C, 204 * C, c209_1};
static const char c210_0[] = "grey81";
static dbEntry e210_0 = {NULL, 207 * C, 207 * C, 207 * C, c210_0};
static const char c211_0[] = "grey82";
static dbEntry e211_0 = {NULL, 209 * C, 209 * C, 209 * C, c211_0};
static const char c212_0[] = "grey83";
static dbEntry e212_0 = {NULL, 212 * C, 212 * C, 212 * C, c212_0};
static const char c213_0[] = "grey84";
static dbEntry e213_0 = {NULL, 214 * C, 214 * C, 214 * C, c213_0};
static const char c214_0[] = "grey85";
static dbEntry e214_0 = {NULL, 217 * C, 217 * C, 217 * C, c214_0};
static const char c215_0[] = "cyan";
static dbEntry e215_0 = {NULL, 0 * C, 255 * C, 255 * C, c215_0};
static const char c215_1[] = "grey86";
static dbEntry e215_1 = {&e215_0, 219 * C, 219 * C, 219 * C, c215_1};
static const char c216_0[] = "grey87";
static dbEntry e216_0 = {NULL, 222 * C, 222 * C, 222 * C, c216_0};
static const char c217_0[] = "palegreen1";
static dbEntry e217_0 = {NULL, 154 * C, 255 * C, 154 * C, c217_0};
static const char c217_1[] = "palegreen2";
static dbEntry e217_1 = {&e217_0, 144 * C, 238 * C, 144 * C, c217_1};
static const char c217_2[] = "palegreen3";
static dbEntry e217_2 = {&e217_1, 124 * C, 205 * C, 124 * C, c217_2};
static const char c217_3[] = "grey88";
static dbEntry e217_3 = {&e217_2, 224 * C, 224 * C, 224 * C, c217_3};
static const char c218_0[] = "grey89";
static dbEntry e218_0 = {NULL, 227 * C, 227 * C, 227 * C, c218_0};
static const char c220_0[] = "mediumvioletred";
static dbEntry e220_0 = {NULL, 199 * C, 21 * C, 133 * C, c220_0};
static const char c221_0[] = "palegreen4";
static dbEntry e221_0 = {NULL, 84 * C, 139 * C, 84 * C, c221_0};
static const char c222_0[] = "darkslateblue";
static dbEntry e222_0 = {NULL, 72 * C, 61 * C, 139 * C, c222_0};
static const char c222_1[] = "lightslateblue";
static dbEntry e222_1 = {&e222_0, 132 * C, 112 * C, 255 * C, c222_1};
static const char c223_0[] = "mediumseagreen";
static dbEntry e223_0 = {NULL, 60 * C, 179 * C, 113 * C, c223_0};
static const char c223_1[] = "coral1";
static dbEntry e223_1 = {&e223_0, 255 * C, 114 * C, 86 * C, c223_1};
static const char c224_0[] = "lightgrey";
static dbEntry e224_0 = {NULL, 211 * C, 211 * C, 211 * C, c224_0};
static const char c224_1[] = "lightgray";
static dbEntry e224_1 = {&e224_0, 211 * C, 211 * C, 211 * C, c224_1};
static const char c224_2[] = "coral2";
static dbEntry e224_2 = {&e224_1, 238 * C, 106 * C, 80 * C, c224_2};
static const char c225_0[] = "coral3";
static dbEntry e225_0 = {NULL, 205 * C, 91 * C, 69 * C, c225_0};
static const char c225_1[] = "grey90";
static dbEntry e225_1 = {&e225_0, 229 * C, 229 * C, 229 * C, c225_1};
static const char c226_0[] = "coral4";
static dbEntry e226_0 = {NULL, 139 * C, 62 * C, 47 * C, c226_0};
static const char c226_1[] = "grey91";
static dbEntry e226_1 = {&e226_0, 232 * C, 232 * C, 232 * C, c226_1};
static const char c227_0[] = "grey92";
static dbEntry e227_0 = {NULL, 235 * C, 235 * C, 235 * C, c227_0};
static const char c228_0[] = "grey93";
static dbEntry e228_0 = {NULL, 237 * C, 237 * C, 237 * C, c228_0};
static const char c229_0[] = "grey94";
static dbEntry e229_0 = {NULL, 240 * C, 240 * C, 240 * C, c229_0};
static const char c230_0[] = "grey95";
static dbEntry e230_0 = {NULL, 242 * C, 242 * C, 242 * C, c230_0};
static const char c231_0[] = "grey96";
static dbEntry e231_0 = {NULL, 245 * C, 245 * C, 245 * C, c231_0};
static const char c232_0[] = "grey97";
static dbEntry e232_0 = {NULL, 247 * C, 247 * C, 247 * C, c232_0};
static const char c233_0[] = "grey98";
static dbEntry e233_0 = {NULL, 250 * C, 250 * C, 250 * C, c233_0};
static const char c234_0[] = "violet";
static dbEntry e234_0 = {NULL, 238 * C, 130 * C, 238 * C, c234_0};
static const char c234_1[] = "grey99";
static dbEntry e234_1 = {&e234_0, 252 * C, 252 * C, 252 * C, c234_1};
static const char c235_0[] = "darkturquoise";
static dbEntry e235_0 = {NULL, 0 * C, 206 * C, 209 * C, c235_0};
static const char c237_0[] = "moccasin";
static dbEntry e237_0 = {NULL, 255 * C, 228 * C, 181 * C, c237_0};
static const char c239_0[] = "darkgoldenrod";
static dbEntry e239_0 = {NULL, 184 * C, 134 * C, 11 * C, c239_0};
static const char c240_0[] = "paleturquoise";
static dbEntry e240_0 = {NULL, 175 * C, 238 * C, 238 * C, c240_0};
static const char c240_1[] = "red";
static dbEntry e240_1 = {&e240_0, 255 * C, 0 * C, 0 * C, c240_1};
static const char c242_0[] = "limegreen";
static dbEntry e242_0 = {NULL, 50 * C, 205 * C, 50 * C, c242_0};
static const char c242_1[] = "orange";
static dbEntry e242_1 = {&e242_0, 255 * C, 165 * C, 0 * C, c242_1};
static const char c243_0[] = "chocolate2";
static dbEntry e243_0 = {NULL, 238 * C, 118 * C, 33 * C, c243_0};
static const char c244_0[] = "chocolate1";
static dbEntry e244_0 = {NULL, 255 * C, 127 * C, 36 * C, c244_0};
static const char c244_1[] = "chocolate3";
static dbEntry e244_1 = {&e244_0, 205 * C, 102 * C, 29 * C, c244_1};
static const char c245_0[] = "gainsboro";
static dbEntry e245_0 = {NULL, 220 * C, 220 * C, 220 * C, c245_0};
static const char c247_0[] = "chocolate4";
static dbEntry e247_0 = {NULL, 139 * C, 69 * C, 19 * C, c247_0};
static const char c256_0[] = "blue";
static dbEntry e256_0 = {NULL, 0 * C, 0 * C, 255 * C, c256_0};
static const char c256_1[] = "honeydew4";
static dbEntry e256_1 = {&e256_0, 131 * C, 139 * C, 131 * C, c256_1};
static const char c257_0[] = "honeydew1";
static dbEntry e257_0 = {NULL, 240 * C, 255 * C, 240 * C, c257_0};
static const char c258_0[] = "honeydew2";
static dbEntry e258_0 = {NULL, 224 * C, 238 * C, 224 * C, c258_0};
static const char c259_0[] = "honeydew3";
static dbEntry e259_0 = {NULL, 193 * C, 205 * C, 193 * C, c259_0};
static const char c264_0[] = "darkgoldenrod1";
static dbEntry e264_0 = {NULL, 255 * C, 185 * C, 15 * C, c264_0};
static const char c265_0[] = "darkgoldenrod2";
static dbEntry e265_0 = {NULL, 238 * C, 173 * C, 14 * C, c265_0};
static const char c266_0[] = "lavenderblush1";
static dbEntry e266_0 = {NULL, 255 * C, 240 * C, 245 * C, c266_0};
static const char c266_1[] = "azure1";
static dbEntry e266_1 = {&e266_0, 240 * C, 255 * C, 255 * C, c266_1};
static const char c266_2[] = "darkgoldenrod3";
static dbEntry e266_2 = {&e266_1, 205 * C, 149 * C, 12 * C, c266_2};
static const char c267_0[] = "lavenderblush2";
static dbEntry e267_0 = {NULL, 238 * C, 224 * C, 229 * C, c267_0};
static const char c267_1[] = "azure2";
static dbEntry e267_1 = {&e267_0, 224 * C, 238 * C, 238 * C, c267_1};
static const char c267_2[] = "darkgoldenrod4";
static dbEntry e267_2 = {&e267_1, 139 * C, 101 * C, 8 * C, c267_2};
static const char c268_0[] = "sienna";
static dbEntry e268_0 = {NULL, 160 * C, 82 * C, 45 * C, c268_0};
static const char c268_1[] = "lavenderblush3";
static dbEntry e268_1 = {&e268_0, 205 * C, 193 * C, 197 * C, c268_1};
static const char c268_2[] = "azure3";
static dbEntry e268_2 = {&e268_1, 193 * C, 205 * C, 205 * C, c268_2};
static const char c269_0[] = "lavenderblush4";
static dbEntry e269_0 = {NULL, 139 * C, 131 * C, 134 * C, c269_0};
static const char c269_1[] = "azure4";
static dbEntry e269_1 = {&e269_0, 131 * C, 139 * C, 139 * C, c269_1};
static const char c272_0[] = "lemonchiffon";
static dbEntry e272_0 = {NULL, 255 * C, 250 * C, 205 * C, c272_0};
static const char c277_0[] = "bisque1";
static dbEntry e277_0 = {NULL, 255 * C, 228 * C, 196 * C, c277_0};
static const char c277_1[] = "burlywood4";
static dbEntry e277_1 = {&e277_0, 139 * C, 115 * C, 85 * C, c277_1};
static const char c278_0[] = "burlywood1";
static dbEntry e278_0 = {NULL, 255 * C, 211 * C, 155 * C, c278_0};
static const char c279_0[] = "bisque2";
static dbEntry e279_0 = {NULL, 238 * C, 213 * C, 183 * C, c279_0};
static const char c279_1[] = "bisque3";
static dbEntry e279_1 = {&e279_0, 205 * C, 183 * C, 158 * C, c279_1};
static const char c279_2[] = "burlywood2";
static dbEntry e279_2 = {&e279_1, 238 * C, 197 * C, 145 * C, c279_2};
static const char c280_0[] = "orangered";
static dbEntry e280_0 = {NULL, 255 * C, 69 * C, 0 * C, c280_0};
static const char c280_1[] = "burlywood3";
static dbEntry e280_1 = {&e280_0, 205 * C, 170 * C, 125 * C, c280_1};
static const char c281_0[] = "bisque4";
static dbEntry e281_0 = {NULL, 139 * C, 125 * C, 107 * C, c281_0};
static const char c283_0[] = "darkorange";
static dbEntry e283_0 = {NULL, 255 * C, 140 * C, 0 * C, c283_0};
static const char c286_0[] = "lavender";
static dbEntry e286_0 = {NULL, 230 * C, 230 * C, 250 * C, c286_0};
static const char c286_1[] = "orchid";
static dbEntry e286_1 = {&e286_0, 218 * C, 112 * C, 214 * C, c286_1};
static const char c287_0[] = "green";
static dbEntry e287_0 = {NULL, 0 * C, 255 * C, 0 * C, c287_0};
static const char c288_0[] = "ivory";
static dbEntry e288_0 = {NULL, 255 * C, 255 * C, 240 * C, c288_0};
static const char c291_0[] = "slategray2";
static dbEntry e291_0 = {NULL, 185 * C, 211 * C, 238 * C, c291_0};
static const char c292_0[] = "slategray1";
static dbEntry e292_0 = {NULL, 198 * C, 226 * C, 255 * C, c292_0};
static const char c292_1[] = "slategray3";
static dbEntry e292_1 = {&e292_0, 159 * C, 182 * C, 205 * C, c292_1};
static const char c294_0[] = "navajowhite";
static dbEntry e294_0 = {NULL, 255 * C, 222 * C, 173 * C, c294_0};
static const char c294_1[] = "darkolivegreen2";
static dbEntry e294_1 = {&e294_0, 188 * C, 238 * C, 104 * C, c294_1};
static const char c295_0[] = "slategray4";
static dbEntry e295_0 = {NULL, 108 * C, 123 * C, 139 * C, c295_0};
static const char c295_1[] = "darkolivegreen1";
static dbEntry e295_1 = {&e295_0, 202 * C, 255 * C, 112 * C, c295_1};
static const char c295_2[] = "darkolivegreen3";
static dbEntry e295_2 = {&e295_1, 162 * C, 205 * C, 90 * C, c295_2};
static const char c296_0[] = "aquamarine1";
static dbEntry e296_0 = {NULL, 127 * C, 255 * C, 212 * C, c296_0};
static const char c296_1[] = "aquamarine2";
static dbEntry e296_1 = {&e296_0, 118 * C, 238 * C, 198 * C, c296_1};
static const char c296_2[] = "aquamarine3";
static dbEntry e296_2 = {&e296_1, 102 * C, 205 * C, 170 * C, c296_2};
static const char c297_0[] = "khaki";
static dbEntry e297_0 = {NULL, 240 * C, 230 * C, 140 * C, c297_0};
static const char c298_0[] = "darkolivegreen4";
static dbEntry e298_0 = {NULL, 110 * C, 139 * C, 61 * C, c298_0};
static const char c300_0[] = "aquamarine4";
static dbEntry e300_0 = {NULL, 69 * C, 139 * C, 116 * C, c300_0};
static const char c301_0[] = "azure";
static dbEntry e301_0 = {NULL, 240 * C, 255 * C, 255 * C, c301_0};
static const char c301_1[] = "aquamarine";
static dbEntry e301_1 = {&e301_0, 127 * C, 255 * C, 212 * C, c301_1};
static const char c302_0[] = "darkgray";
static dbEntry e302_0 = {NULL, 169 * C, 169 * C, 169 * C, c302_0};
static const char c304_0[] = "thistle1";
static dbEntry e304_0 = {NULL, 255 * C, 225 * C, 255 * C, c304_0};
static const char c304_1[] = "thistle2";
static dbEntry e304_1 = {&e304_0, 238 * C, 210 * C, 238 * C, c304_1};
static const char c304_2[] = "thistle3";
static dbEntry e304_2 = {&e304_1, 205 * C, 181 * C, 205 * C, c304_2};
static const char c304_3[] = "thistle4";
static dbEntry e304_3 = {&e304_2, 139 * C, 123 * C, 139 * C, c304_3};
static const char c312_0[] = "red1";
static dbEntry e312_0 = {NULL, 255 * C, 0 * C, 0 * C, c312_0};
static const char c313_0[] = "red2";
static dbEntry e313_0 = {NULL, 238 * C, 0 * C, 0 * C, c313_0};
static const char c314_0[] = "blanchedalmond";
static dbEntry e314_0 = {NULL, 255 * C, 235 * C, 205 * C, c314_0};
static const char c314_1[] = "royalblue1";
static dbEntry e314_1 = {&e314_0, 72 * C, 118 * C, 255 * C, c314_1};
static const char c314_2[] = "red3";
static dbEntry e314_2 = {&e314_1, 205 * C, 0 * C, 0 * C, c314_2};
static const char c314_3[] = "purple1";
static dbEntry e314_3 = {&e314_2, 155 * C, 48 * C, 255 * C, c314_3};
static const char c314_4[] = "purple2";
static dbEntry e314_4 = {&e314_3, 145 * C, 44 * C, 238 * C, c314_4};
static const char c314_5[] = "purple3";
static dbEntry e314_5 = {&e314_4, 125 * C, 38 * C, 205 * C, c314_5};
static const char c314_6[] = "purple4";
static dbEntry e314_6 = {&e314_5, 85 * C, 26 * C, 139 * C, c314_6};
static const char c315_0[] = "snow";
static dbEntry e315_0 = {NULL, 255 * C, 250 * C, 250 * C, c315_0};
static const char c315_1[] = "darkorchid";
static dbEntry e315_1 = {&e315_0, 153 * C, 50 * C, 204 * C, c315_1};
static const char c315_2[] = "royalblue2";
static dbEntry e315_2 = {&e315_1, 67 * C, 110 * C, 238 * C, c315_2};
static const char c315_3[] = "red4";
static dbEntry e315_3 = {&e315_2, 139 * C, 0 * C, 0 * C, c315_3};
static const char c316_0[] = "palegreen";
static dbEntry e316_0 = {NULL, 152 * C, 251 * C, 152 * C, c316_0};
static const char c316_1[] = "royalblue3";
static dbEntry e316_1 = {&e316_0, 58 * C, 95 * C, 205 * C, c316_1};
static const char c317_0[] = "lavenderblush";
static dbEntry e317_0 = {NULL, 255 * C, 240 * C, 245 * C, c317_0};
static const char c317_1[] = "royalblue4";
static dbEntry e317_1 = {&e317_0, 39 * C, 64 * C, 139 * C, c317_1};
static const char c318_0[] = "aliceblue";
static dbEntry e318_0 = {NULL, 240 * C, 248 * C, 255 * C, c318_0};
static const char c319_0[] = "royalblue";
static dbEntry e319_0 = {NULL, 65 * C, 105 * C, 225 * C, c319_0};
static const char c322_0[] = "dimgray";
static dbEntry e322_0 = {NULL, 105 * C, 105 * C, 105 * C, c322_0};
static const char c322_1[] = "dimgrey";
static dbEntry e322_1 = {&e322_0, 105 * C, 105 * C, 105 * C, c322_1};
static const char c332_0[] = "hotpink2";
static dbEntry e332_0 = {NULL, 238 * C, 106 * C, 167 * C, c332_0};
static const char c332_1[] = "hotpink4";
static dbEntry e332_1 = {&e332_0, 139 * C, 58 * C, 98 * C, c332_1};
static const char c333_0[] = "hotpink1";
static dbEntry e333_0 = {NULL, 255 * C, 110 * C, 180 * C, c333_0};
static const char c333_1[] = "hotpink3";
static dbEntry e333_1 = {&e333_0, 205 * C, 96 * C, 144 * C, c333_1};
static const char c335_0[] = "cadetblue4";
static dbEntry e335_0 = {NULL, 83 * C, 134 * C, 139 * C, c335_0};
static const char c336_0[] = "ghostwhite";
static dbEntry e336_0 = {NULL, 248 * C, 248 * C, 255 * C, c336_0};
static const char c336_1[] = "magenta";
static dbEntry e336_1 = {&e336_0, 255 * C, 0 * C, 255 * C, c336_1};
static const char c336_2[] = "purple";
static dbEntry e336_2 = {&e336_1, 160 * C, 32 * C, 240 * C, c336_2};
static const char c336_3[] = "cadetblue1";
static dbEntry e336_3 = {&e336_2, 152 * C, 245 * C, 255 * C, c336_3};
static const char c337_0[] = "cadetblue2";
static dbEntry e337_0 = {NULL, 142 * C, 229 * C, 238 * C, c337_0};
static const char c338_0[] = "cadetblue3";
static dbEntry e338_0 = {NULL, 122 * C, 197 * C, 205 * C, c338_0};
static const char c339_0[] = "goldenrod";
static dbEntry e339_0 = {NULL, 218 * C, 165 * C, 32 * C, c339_0};
static const char c340_0[] = "chartreuse1";
static dbEntry e340_0 = {NULL, 127 * C, 255 * C, 0 * C, c340_0};
static const char c340_1[] = "chartreuse2";
static dbEntry e340_1 = {&e340_0, 118 * C, 238 * C, 0 * C, c340_1};
static const char c340_2[] = "chartreuse3";
static dbEntry e340_2 = {&e340_1, 102 * C, 205 * C, 0 * C, c340_2};
static const char c342_0[] = "papayawhip";
static dbEntry e342_0 = {NULL, 255 * C, 239 * C, 213 * C, c342_0};
static const char c342_1[] = "lightgoldenrod";
static dbEntry e342_1 = {&e342_0, 238 * C, 221 * C, 130 * C, c342_1};
static const char c343_0[] = "orange2";
static dbEntry e343_0 = {NULL, 238 * C, 154 * C, 0 * C, c343_0};
static const char c343_1[] = "orange4";
static dbEntry e343_1 = {&e343_0, 139 * C, 90 * C, 0 * C, c343_1};
static const char c344_0[] = "chartreuse4";
static dbEntry e344_0 = {NULL, 69 * C, 139 * C, 0 * C, c344_0};
static const char c344_1[] = "orange1";
static dbEntry e344_1 = {&e344_0, 255 * C, 165 * C, 0 * C, c344_1};
static const char c344_2[] = "orange3";
static dbEntry e344_2 = {&e344_1, 205 * C, 133 * C, 0 * C, c344_2};
static const char c346_0[] = "steelblue";
static dbEntry e346_0 = {NULL, 70 * C, 130 * C, 180 * C, c346_0};
static const char c364_0[] = "rosybrown1";
static dbEntry e364_0 = {NULL, 255 * C, 193 * C, 193 * C, c364_0};
static const char c364_1[] = "rosybrown2";
static dbEntry e364_1 = {&e364_0, 238 * C, 180 * C, 180 * C, c364_1};
static const char c364_2[] = "rosybrown3";
static dbEntry e364_2 = {&e364_1, 205 * C, 155 * C, 155 * C, c364_2};
static const char c364_3[] = "rosybrown4";
static dbEntry e364_3 = {&e364_2, 139 * C, 105 * C, 105 * C, c364_3};
static const char c366_0[] = "lightsteelblue";
static dbEntry e366_0 = {NULL, 176 * C, 196 * C, 222 * C, c366_0};
static const char c366_1[] = "skyblue2";
static dbEntry e366_1 = {&e366_0, 126 * C, 192 * C, 238 * C, c366_1};
static const char c366_2[] = "darkgrey";
static dbEntry e366_2 = {&e366_1, 169 * C, 169 * C, 169 * C, c366_2};
static const char c367_0[] = "skyblue1";
static dbEntry e367_0 = {NULL, 135 * C, 206 * C, 255 * C, c367_0};
static const char c367_1[] = "skyblue3";
static dbEntry e367_1 = {&e367_0, 108 * C, 166 * C, 205 * C, c367_1};
static const char c368_0[] = "mediumpurple";
static dbEntry e368_0 = {NULL, 147 * C, 112 * C, 219 * C, c368_0};
static const char c368_1[] = "darkslategray1";
static dbEntry e368_1 = {&e368_0, 151 * C, 255 * C, 255 * C, c368_1};
static const char c369_0[] = "darkviolet";
static dbEntry e369_0 = {NULL, 148 * C, 0 * C, 211 * C, c369_0};
static const char c369_1[] = "darkslategray2";
static dbEntry e369_1 = {&e369_0, 141 * C, 238 * C, 238 * C, c369_1};
static const char c370_0[] = "skyblue4";
static dbEntry e370_0 = {NULL, 74 * C, 112 * C, 139 * C, c370_0};
static const char c370_1[] = "darkslategray3";
static dbEntry e370_1 = {&e370_0, 121 * C, 205 * C, 205 * C, c370_1};
static const char c371_0[] = "darkslategray4";
static dbEntry e371_0 = {NULL, 82 * C, 139 * C, 139 * C, c371_0};
static const char c376_0[] = "plum";
static dbEntry e376_0 = {NULL, 221 * C, 160 * C, 221 * C, c376_0};
static const char c377_0[] = "midnightblue";
static dbEntry e377_0 = {NULL, 25 * C, 25 * C, 112 * C, c377_0};
static const char c379_0[] = "lightgoldenrod1";
static dbEntry e379_0 = {NULL, 255 * C, 236 * C, 139 * C, c379_0};
static const char c380_0[] = "lightgoldenrod2";
static dbEntry e380_0 = {NULL, 238 * C, 220 * C, 130 * C, c380_0};
static const char c381_0[] = "lightgoldenrod3";
static dbEntry e381_0 = {NULL, 205 * C, 190 * C, 112 * C, c381_0};
static const char c382_0[] = "lightgoldenrod4";
static dbEntry e382_0 = {NULL, 139 * C, 129 * C, 76 * C, c382_0};
static const char c383_0[] = "indianred";
static dbEntry e383_0 = {NULL, 205 * C, 92 * C, 92 * C, c383_0};
static const char c384_0[] = "yellow";
static dbEntry e384_0 = {NULL, 255 * C, 255 * C, 0 * C, c384_0};
static const char c386_0[] = "olivedrab1";
static dbEntry e386_0 = {NULL, 192 * C, 255 * C, 62 * C, c386_0};
static const char c387_0[] = "olivedrab2";
static dbEntry e387_0 = {NULL, 179 * C, 238 * C, 58 * C, c387_0};
static const char c388_0[] = "olivedrab3";
static dbEntry e388_0 = {NULL, 154 * C, 205 * C, 50 * C, c388_0};
static const char c389_0[] = "slateblue";
static dbEntry e389_0 = {NULL, 106 * C, 90 * C, 205 * C, c389_0};
static const char c389_1[] = "lightsalmon";
static dbEntry e389_1 = {&e389_0, 255 * C, 160 * C, 122 * C, c389_1};
static const char c389_2[] = "olivedrab4";
static dbEntry e389_2 = {&e389_1, 105 * C, 139 * C, 34 * C, c389_2};
static const char c390_0[] = "lightyellow";
static dbEntry e390_0 = {NULL, 255 * C, 255 * C, 224 * C, c390_0};
static const char c393_0[] = "navajowhite1";
static dbEntry e393_0 = {NULL, 255 * C, 222 * C, 173 * C, c393_0};
static const char c394_0[] = "navajowhite2";
static dbEntry e394_0 = {NULL, 238 * C, 207 * C, 161 * C, c394_0};
static const char c395_0[] = "firebrick";
static dbEntry e395_0 = {NULL, 178 * C, 34 * C, 34 * C, c395_0};
static const char c395_1[] = "navajowhite3";
static dbEntry e395_1 = {&e395_0, 205 * C, 179 * C, 139 * C, c395_1};
static const char c395_2[] = "indianred1";
static dbEntry e395_2 = {&e395_1, 255 * C, 106 * C, 106 * C, c395_2};
static const char c395_3[] = "indianred2";
static dbEntry e395_3 = {&e395_2, 238 * C, 99 * C, 99 * C, c395_3};
static const char c395_4[] = "indianred3";
static dbEntry e395_4 = {&e395_3, 205 * C, 85 * C, 85 * C, c395_4};
static const char c395_5[] = "indianred4";
static dbEntry e395_5 = {&e395_4, 139 * C, 58 * C, 58 * C, c395_5};
static const char c396_0[] = "navajowhite4";
static dbEntry e396_0 = {NULL, 139 * C, 121 * C, 94 * C, c396_0};
static const char c399_0[] = "cornsilk";
static dbEntry e399_0 = {NULL, 255 * C, 248 * C, 220 * C, c399_0};
static const char c399_1[] = "mistyrose";
static dbEntry e399_1 = {&e399_0, 255 * C, 228 * C, 225 * C, c399_1};
static const char c408_0[] = "gold";
static dbEntry e408_0 = {NULL, 255 * C, 215 * C, 0 * C, c408_0};
static const char c414_0[] = "sandybrown";
static dbEntry e414_0 = {NULL, 244 * C, 164 * C, 96 * C, c414_0};
static const char c416_0[] = "hotpink";
static dbEntry e416_0 = {NULL, 255 * C, 105 * C, 180 * C, c416_0};
static const char c417_0[] = "rosybrown";
static dbEntry e417_0 = {NULL, 188 * C, 143 * C, 143 * C, c417_0};
static const char c419_0[] = "maroon1";
static dbEntry e419_0 = {NULL, 255 * C, 52 * C, 179 * C, c419_0};
static const char c419_1[] = "maroon2";
static dbEntry e419_1 = {&e419_0, 238 * C, 48 * C, 167 * C, c419_1};
static const char c419_2[] = "maroon3";
static dbEntry e419_2 = {&e419_1, 205 * C, 41 * C, 144 * C, c419_2};
static const char c420_0[] = "palevioletred2";
static dbEntry e420_0 = {NULL, 238 * C, 121 * C, 159 * C, c420_0};
static const char c421_0[] = "palevioletred1";
static dbEntry e421_0 = {NULL, 255 * C, 130 * C, 171 * C, c421_0};
static const char c421_1[] = "palevioletred3";
static dbEntry e421_1 = {&e421_0, 205 * C, 104 * C, 137 * C, c421_1};
static const char c423_0[] = "cyan1";
static dbEntry e423_0 = {NULL, 0 * C, 255 * C, 255 * C, c423_0};
static const char c423_1[] = "maroon4";
static dbEntry e423_1 = {&e423_0, 139 * C, 28 * C, 98 * C, c423_1};
static const char c424_0[] = "cyan2";
static dbEntry e424_0 = {NULL, 0 * C, 238 * C, 238 * C, c424_0};
static const char c424_1[] = "palevioletred4";
static dbEntry e424_1 = {&e424_0, 139 * C, 71 * C, 93 * C, c424_1};
static const char c424_2[] = "orchid2";
static dbEntry e424_2 = {&e424_1, 238 * C, 122 * C, 233 * C, c424_2};
static const char c424_3[] = "orchid4";
static dbEntry e424_3 = {&e424_2, 139 * C, 71 * C, 137 * C, c424_3};
static const char c425_0[] = "cyan3";
static dbEntry e425_0 = {NULL, 0 * C, 205 * C, 205 * C, c425_0};
static const char c425_1[] = "orchid1";
static dbEntry e425_1 = {&e425_0, 255 * C, 131 * C, 250 * C, c425_1};
static const char c425_2[] = "orchid3";
static dbEntry e425_2 = {&e425_1, 205 * C, 105 * C, 201 * C, c425_2};
static const char c426_0[] = "cyan4";
static dbEntry e426_0 = {NULL, 0 * C, 139 * C, 139 * C, c426_0};
static const char c427_0[] = "cornsilk1";
static dbEntry e427_0 = {NULL, 255 * C, 248 * C, 220 * C, c427_0};
static const char c429_0[] = "cornsilk2";
static dbEntry e429_0 = {NULL, 238 * C, 232 * C, 205 * C, c429_0};
static const char c429_1[] = "cornsilk3";
static dbEntry e429_1 = {&e429_0, 205 * C, 200 * C, 177 * C, c429_1};
static const char c429_2[] = "tomato1";
static dbEntry e429_2 = {&e429_1, 255 * C, 99 * C, 71 * C, c429_2};
static const char c429_3[] = "tomato2";
static dbEntry e429_3 = {&e429_2, 238 * C, 92 * C, 66 * C, c429_3};
static const char c429_4[] = "tomato3";
static dbEntry e429_4 = {&e429_3, 205 * C, 79 * C, 57 * C, c429_4};
static const char c431_0[] = "cornsilk4";
static dbEntry e431_0 = {NULL, 139 * C, 136 * C, 120 * C, c431_0};
static const char c433_0[] = "tomato4";
static dbEntry e433_0 = {NULL, 139 * C, 54 * C, 38 * C, c433_0};
static const char c435_0[] = "darkseagreen1";
static dbEntry e435_0 = {NULL, 193 * C, 255 * C, 193 * C, c435_0};
static const char c435_1[] = "darkseagreen4";
static dbEntry e435_1 = {&e435_0, 105 * C, 139 * C, 105 * C, c435_1};
static const char c437_0[] = "darkseagreen2";
static dbEntry e437_0 = {NULL, 180 * C, 238 * C, 180 * C, c437_0};
static const char c437_1[] = "darkseagreen3";
static dbEntry e437_1 = {&e437_0, 155 * C, 205 * C, 155 * C, c437_1};
static const char c441_0[] = "tomato";
static dbEntry e441_0 = {NULL, 255 * C, 99 * C, 71 * C, c441_0};
static const char c443_0[] = "deeppink";
static dbEntry e443_0 = {NULL, 255 * C, 20 * C, 147 * C, c443_0};
static const char c443_1[] = "mediumpurple1";
static dbEntry e443_1 = {&e443_0, 171 * C, 130 * C, 255 * C, c443_1};
static const char c444_0[] = "white";
static dbEntry e444_0 = {NULL, 255 * C, 255 * C, 255 * C, c444_0};
static const char c444_1[] = "dodgerblue";
static dbEntry e444_1 = {&e444_0, 30 * C, 144 * C, 255 * C, c444_1};
static const char c444_2[] = "plum1";
static dbEntry e444_2 = {&e444_1, 255 * C, 187 * C, 255 * C, c444_2};
static const char c444_3[] = "mediumpurple2";
static dbEntry e444_3 = {&e444_2, 159 * C, 121 * C, 238 * C, c444_3};
static const char c445_0[] = "gold1";
static dbEntry e445_0 = {NULL, 255 * C, 215 * C, 0 * C, c445_0};
static const char c445_1[] = "plum2";
static dbEntry e445_1 = {&e445_0, 238 * C, 174 * C, 238 * C, c445_1};
static const char c445_2[] = "mediumpurple3";
static dbEntry e445_2 = {&e445_1, 137 * C, 104 * C, 205 * C, c445_2};
static const char c446_0[] = "gold2";
static dbEntry e446_0 = {NULL, 238 * C, 201 * C, 0 * C, c446_0};
static const char c446_1[] = "plum3";
static dbEntry e446_1 = {&e446_0, 205 * C, 150 * C, 205 * C, c446_1};
static const char c446_2[] = "mediumpurple4";
static dbEntry e446_2 = {&e446_1, 93 * C, 71 * C, 139 * C, c446_2};
static const char c447_0[] = "gold3";
static dbEntry e447_0 = {NULL, 205 * C, 173 * C, 0 * C, c447_0};
static const char c447_1[] = "plum4";
static dbEntry e447_1 = {&e447_0, 139 * C, 102 * C, 139 * C, c447_1};
static const char c448_0[] = "seashell1";
static dbEntry e448_0 = {NULL, 255 * C, 245 * C, 238 * C, c448_0};
static const char c448_1[] = "gold4";
static dbEntry e448_1 = {&e448_0, 139 * C, 117 * C, 0 * C, c448_1};
static const char c449_0[] = "seashell2";
static dbEntry e449_0 = {NULL, 238 * C, 229 * C, 222 * C, c449_0};
static const char c450_0[] = "seashell3";
static dbEntry e450_0 = {NULL, 205 * C, 197 * C, 191 * C, c450_0};
static const char c451_0[] = "brown";
static dbEntry e451_0 = {NULL, 165 * C, 42 * C, 42 * C, c451_0};
static const char c451_1[] = "seashell4";
static dbEntry e451_1 = {&e451_0, 139 * C, 134 * C, 130 * C, c451_1};
static const char c452_0[] = "turquoise1";
static dbEntry e452_0 = {NULL, 0 * C, 245 * C, 255 * C, c452_0};
static const char c453_0[] = "turquoise2";
static dbEntry e453_0 = {NULL, 0 * C, 229 * C, 238 * C, c453_0};
static const char c453_1[] = "wheat1";
static dbEntry e453_1 = {&e453_0, 255 * C, 231 * C, 186 * C, c453_1};
static const char c454_0[] = "turquoise3";
static dbEntry e454_0 = {NULL, 0 * C, 197 * C, 205 * C, c454_0};
static const char c454_1[] = "wheat2";
static dbEntry e454_1 = {&e454_0, 238 * C, 216 * C, 174 * C, c454_1};
static const char c455_0[] = "turquoise4";
static dbEntry e455_0 = {NULL, 0 * C, 134 * C, 139 * C, c455_0};
static const char c455_1[] = "wheat3";
static dbEntry e455_1 = {&e455_0, 205 * C, 186 * C, 150 * C, c455_1};
static const char c456_0[] = "wheat4";
static dbEntry e456_0 = {NULL, 139 * C, 126 * C, 102 * C, c456_0};
static const char c458_0[] = "coral";
static dbEntry e458_0 = {NULL, 255 * C, 127 * C, 80 * C, c458_0};
static const char c459_0[] = "slateblue2";
static dbEntry e459_0 = {NULL, 122 * C, 103 * C, 238 * C, c459_0};
static const char c460_0[] = "slateblue1";
static dbEntry e460_0 = {NULL, 131 * C, 111 * C, 255 * C, c460_0};
static const char c460_1[] = "slateblue3";
static dbEntry e460_1 = {&e460_0, 105 * C, 89 * C, 205 * C, c460_1};
static const char c463_0[] = "slateblue4";
static dbEntry e463_0 = {NULL, 71 * C, 60 * C, 139 * C, c463_0};
static const char c467_0[] = "violetred2";
static dbEntry e467_0 = {NULL, 238 * C, 58 * C, 140 * C, c467_0};
static const char c468_0[] = "violetred1";
static dbEntry e468_0 = {NULL, 255 * C, 62 * C, 150 * C, c468_0};
static const char c468_1[] = "violetred3";
static dbEntry e468_1 = {&e468_0, 205 * C, 50 * C, 120 * C, c468_1};
static const char c471_0[] = "violetred4";
static dbEntry e471_0 = {NULL, 139 * C, 34 * C, 82 * C, c471_0};
static const char c471_1[] = "darkred";
static dbEntry e471_1 = {&e471_0, 139 * C, 0 * C, 0 * C, c471_1};
static const char c472_0[] = "whitesmoke";
static dbEntry e472_0 = {NULL, 245 * C, 245 * C, 245 * C, c472_0};
static const char c479_0[] = "palegoldenrod";
static dbEntry e479_0 = {NULL, 238 * C, 232 * C, 170 * C, c479_0};
static const char c480_0[] = "springgreen";
static dbEntry e480_0 = {NULL, 0 * C, 255 * C, 127 * C, c480_0};
static const char c482_0[] = "darkmagenta";
static dbEntry e482_0 = {NULL, 139 * C, 0 * C, 139 * C, c482_0};
static const char c485_0[] = "mediumorchid1";
static dbEntry e485_0 = {NULL, 224 * C, 102 * C, 255 * C, c485_0};
static const char c486_0[] = "lightblue";
static dbEntry e486_0 = {NULL, 173 * C, 216 * C, 230 * C, c486_0};
static const char c486_1[] = "mediumturquoise";
static dbEntry e486_1 = {&e486_0, 72 * C, 209 * C, 204 * C, c486_1};
static const char c486_2[] = "lightcyan";
static dbEntry e486_2 = {&e486_1, 224 * C, 255 * C, 255 * C, c486_2};
static const char c486_3[] = "tan1";
static dbEntry e486_3 = {&e486_2, 255 * C, 165 * C, 79 * C, c486_3};
static const char c486_4[] = "mediumorchid2";
static dbEntry e486_4 = {&e486_3, 209 * C, 95 * C, 238 * C, c486_4};
static const char c487_0[] = "tan2";
static dbEntry e487_0 = {NULL, 238 * C, 154 * C, 73 * C, c487_0};
static const char c487_1[] = "mediumorchid3";
static dbEntry e487_1 = {&e487_0, 180 * C, 82 * C, 205 * C, c487_1};
static const char c488_0[] = "tan3";
static dbEntry e488_0 = {NULL, 205 * C, 133 * C, 63 * C, c488_0};
static const char c488_1[] = "mediumorchid4";
static dbEntry e488_1 = {&e488_0, 122 * C, 55 * C, 139 * C, c488_1};
static const char c489_0[] = "skyblue";
static dbEntry e489_0 = {NULL, 135 * C, 206 * C, 235 * C, c489_0};
static const char c489_1[] = "tan4";
static dbEntry e489_1 = {&e489_0, 139 * C, 90 * C, 43 * C, c489_1};
static const char c490_0[] = "snow1";
static dbEntry e490_0 = {NULL, 255 * C, 250 * C, 250 * C, c490_0};
static const char c491_0[] = "snow2";
static dbEntry e491_0 = {NULL, 238 * C, 233 * C, 233 * C, c491_0};
static const char c492_0[] = "snow3";
static dbEntry e492_0 = {NULL, 205 * C, 201 * C, 201 * C, c492_0};
static const char c493_0[] = "snow4";
static dbEntry e493_0 = {NULL, 139 * C, 137 * C, 137 * C, c493_0};
static const char c494_0[] = "forestgreen";
static dbEntry e494_0 = {NULL, 34 * C, 139 * C, 34 * C, c494_0};
static const char c497_0[] = "blueviolet";
static dbEntry e497_0 = {NULL, 138 * C, 43 * C, 226 * C, c497_0};
static const char c499_0[] = "darkslategray";
static dbEntry e499_0 = {NULL, 47 * C, 79 * C, 79 * C, c499_0};
static const char c502_0[] = "powderblue";
static dbEntry e502_0 = {NULL, 176 * C, 224 * C, 230 * C, c502_0};
static const char c510_0[] = "gray";
static dbEntry e510_0 = {NULL, 190 * C, 190 * C, 190 * C, c510_0};

#undef C

dbEntryPtr builtinRGBhashTab[HASHSIZE] = {
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e5_0,
    NULL,
    NULL,
    &e8_0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e14_0,
    NULL,
    &e16_0,
    NULL,
    NULL,
    &e19_0,
    NULL,
    &e21_2,
    &e22_0,
    &e23_2,
    &e24_0,
    NULL,
    &e26_0,
    NULL,
    &e28_4,
    &e29_0,
    &e30_0,
    &e31_0,
    &e32_0,
    &e33_0,
    &e34_2,
    &e35_2,
    &e36_1,
    &e37_1,
    &e38_2,
    &e39_2,
    &e40_2,
    &e41_2,
    &e42_7,
    &e43_2,
    &e44_1,
    &e45_0,
    NULL,
    &e47_1,
    NULL,
    NULL,
    NULL,
    &e51_0,
    &e52_0,
    NULL,
    &e54_0,
    &e55_0,
    &e56_0,
    &e57_1,
    &e58_2,
    &e59_3,
    &e60_1,
    &e61_0,
    &e62_1,
    &e63_0,
    &e64_0,
    &e65_1,
    &e66_2,
    &e67_2,
    &e68_1,
    &e69_1,
    &e70_1,
    &e71_0,
    &e72_0,
    &e73_1,
    &e74_0,
    NULL,
    NULL,
    &e77_0,
    NULL,
    &e79_0,
    NULL,
    &e81_0,
    &e82_0,
    &e83_0,
    &e84_0,
    &e85_0,
    &e86_0,
    &e87_0,
    &e88_0,
    &e89_0,
    &e90_0,
    &e91_1,
    NULL,
    &e93_0,
    NULL,
    &e95_0,
    NULL,
    &e97_1,
    &e98_1,
    &e99_1,
    &e100_2,
    &e101_1,
    &e102_1,
    &e103_1,
    &e104_1,
    &e105_1,
    &e106_2,
    &e107_1,
    &e108_3,
    &e109_0,
    &e110_3,
    &e111_0,
    &e112_5,
    &e113_2,
    &e114_2,
    &e115_3,
    &e116_2,
    &e117_2,
    &e118_2,
    &e119_1,
    &e120_2,
    &e121_1,
    &e122_1,
    NULL,
    &e124_0,
    &e125_1,
    &e126_1,
    &e127_3,
    &e128_1,
    &e129_2,
    &e130_2,
    &e131_2,
    &e132_3,
    &e133_1,
    &e134_1,
    &e135_2,
    &e136_1,
    &e137_1,
    &e138_2,
    &e139_2,
    &e140_0,
    &e141_0,
    &e142_1,
    &e143_0,
    NULL,
    &e145_2,
    &e146_6,
    &e147_3,
    &e148_1,
    &e149_3,
    &e150_1,
    &e151_2,
    &e152_1,
    &e153_2,
    &e154_2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e161_1,
    &e162_2,
    &e163_2,
    &e164_1,
    &e165_1,
    &e166_1,
    &e167_1,
    &e168_3,
    &e169_3,
    &e170_3,
    NULL,
    &e172_0,
    &e173_1,
    &e174_7,
    &e175_2,
    &e176_0,
    &e177_1,
    &e178_1,
    &e179_2,
    &e180_2,
    &e181_1,
    &e182_1,
    &e183_1,
    &e184_3,
    &e185_2,
    &e186_4,
    &e187_1,
    &e188_0,
    NULL,
    NULL,
    NULL,
    NULL,
    &e193_1,
    &e194_1,
    &e195_1,
    &e196_2,
    &e197_1,
    &e198_2,
    &e199_2,
    &e200_3,
    &e201_3,
    &e202_2,
    &e203_0,
    &e204_0,
    &e205_0,
    NULL,
    &e207_1,
    NULL,
    &e209_1,
    &e210_0,
    &e211_0,
    &e212_0,
    &e213_0,
    &e214_0,
    &e215_1,
    &e216_0,
    &e217_3,
    &e218_0,
    NULL,
    &e220_0,
    &e221_0,
    &e222_1,
    &e223_1,
    &e224_2,
    &e225_1,
    &e226_1,
    &e227_0,
    &e228_0,
    &e229_0,
    &e230_0,
    &e231_0,
    &e232_0,
    &e233_0,
    &e234_1,
    &e235_0,
    NULL,
    &e237_0,
    NULL,
    &e239_0,
    &e240_1,
    NULL,
    &e242_1,
    &e243_0,
    &e244_1,
    &e245_0,
    NULL,
    &e247_0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e256_1,
    &e257_0,
    &e258_0,
    &e259_0,
    NULL,
    NULL,
    NULL,
    NULL,
    &e264_0,
    &e265_0,
    &e266_2,
    &e267_2,
    &e268_2,
    &e269_1,
    NULL,
    NULL,
    &e272_0,
    NULL,
    NULL,
    NULL,
    NULL,
    &e277_1,
    &e278_0,
    &e279_2,
    &e280_1,
    &e281_0,
    NULL,
    &e283_0,
    NULL,
    NULL,
    &e286_1,
    &e287_0,
    &e288_0,
    NULL,
    NULL,
    &e291_0,
    &e292_1,
    NULL,
    &e294_1,
    &e295_2,
    &e296_2,
    &e297_0,
    &e298_0,
    NULL,
    &e300_0,
    &e301_1,
    &e302_0,
    NULL,
    &e304_3,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e312_0,
    &e313_0,
    &e314_6,
    &e315_3,
    &e316_1,
    &e317_1,
    &e318_0,
    &e319_0,
    NULL,
    NULL,
    &e322_1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e332_1,
    &e333_1,
    NULL,
    &e335_0,
    &e336_3,
    &e337_0,
    &e338_0,
    &e339_0,
    &e340_2,
    NULL,
    &e342_1,
    &e343_1,
    &e344_2,
    NULL,
    &e346_0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e364_3,
    NULL,
    &e366_2,
    &e367_1,
    &e368_1,
    &e369_1,
    &e370_1,
    &e371_0,
    NULL,
    NULL,
    NULL,
    NULL,
    &e376_0,
    &e377_0,
    NULL,
    &e379_0,
    &e380_0,
    &e381_0,
    &e382_0,
    &e383_0,
    &e384_0,
    NULL,
    &e386_0,
    &e387_0,
    &e388_0,
    &e389_2,
    &e390_0,
    NULL,
    NULL,
    &e393_0,
    &e394_0,
    &e395_5,
    &e396_0,
    NULL,
    NULL,
    &e399_1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e408_0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e414_0,
    NULL,
    &e416_0,
    &e417_0,
    NULL,
    &e419_2,
    &e420_0,
    &e421_1,
    NULL,
    &e423_1,
    &e424_3,
    &e425_2,
    &e426_0,
    &e427_0,
    NULL,
    &e429_4,
    NULL,
    &e431_0,
    NULL,
    &e433_0,
    NULL,
    &e435_1,
    NULL,
    &e437_1,
    NULL,
    NULL,
    NULL,
    &e441_0,
    NULL,
    &e443_1,
    &e444_3,
    &e445_2,
    &e446_2,
    &e447_1,
    &e448_1,
    &e449_0,
    &e450_0,
    &e451_1,
    &e452_0,
    &e453_1,
    &e454_1,
    &e455_1,
    &e456_0,
    NULL,
    &e458_0,
    &e459_0,
    &e460_1,
    NULL,
    NULL,
    &e463_0,
    NULL,
    NULL,
    NULL,
    &e467_0,
    &e468_1,
    NULL,
    NULL,
    &e471_1,
    &e472_0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e479_0,
    &e480_0,
    NULL,
    &e482_0,
    NULL,
    NULL,
    &e485_0,
    &e486_4,
    &e487_1,
    &e488_1,
    &e489_1,
    &e490_0,
    &e491_0,
    &e492_0,
    &e493_0,
    &e494_0,
    NULL,
    NULL,
    &e497_0,
    NULL,
    &e499_0,
    NULL,
    NULL,
    &e502_0,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    &e510_0,
};
